"""
test_steady_flight.py — Steady-state physics test at 30° tether elevation.

The simplest possible flight scenario:

  - Hub starts at the 30° tether-angle equilibrium position (East of anchor).
  - Body Z (rotor axle) is aligned with the tether direction from the start.
  - Collective is set to the open-loop equilibrium value (no ArduPilot).
  - Tether rest length is set so the tether is already taut at the equilibrium
    tension.
  - Wind is steady East.

Because the system starts close to equilibrium (correct position, orientation,
and collective), it should remain near that position.  This is the "simple case"
— no transient from launch, no ArduPilot control loop.

A separate test (test_drift_from_origin, TODO) will cover the harder case of
starting directly above the anchor and letting wind + tether drive equilibrium.

Coordinate frame: NED — X=North, Y=East, Z=Down.  Tether anchor at origin.

steady_state_starting.json is generated by test_generate_ic.py::test_create_ic.
"""
import math
import sys
from pathlib import Path

import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

pytestmark = [pytest.mark.simtest, pytest.mark.timeout(300)]

from types import SimpleNamespace

import mediator as _mediator_module
from aero          import create_aero
import rotor_definition as _rd
from controller    import AltitudeHoldController, TensionPI
from frames        import build_orb_frame
from simtest_runner import PhysicsRunner
from simtest_log   import SimtestLog
from tel           import make_tel
from telemetry_csv import TelRow, write_csv

TetherModel = _mediator_module.TetherModel
_log = SimtestLog(__file__)

# Load rotor definition — single source of truth for all physical constants.
_ROTOR = _rd.default()
_DYN_KW = _ROTOR.dynamics_kwargs()   # mass, I_body, I_spin

# Design tether equilibrium orientation (from beaupoil_2026.yaml) in NED
_BODY_Z_DESIGN = np.array([0.305391, 0.851018, -0.427206])  # NED: T @ ENU
_BODY_Z_DESIGN.flags.writeable = False
_BASE_K_ANG    = 50.0   # N·m·s/rad — angular damping (matches mediator default)
_T_AERO_OFFSET = 45.0   # s — aero ramp already done

# ── Physical constants (all from rotor definition) ────────────────────────────
MASS          = _DYN_KW["mass"]           # kg
G             = 9.81                       # m/s²
WEIGHT        = MASS * G                   # N
WIND   = np.array([0.0, 10.0, 0.0])       # NED: 10 m/s East = Y axis
WIND.flags.writeable = False

DT     = 2.5e-3                            # s  (400 Hz)

# ── Tether geometry ───────────────────────────────────────────────────────────
ELEV_DEG = 30.0
ELEV_RAD = math.radians(ELEV_DEG)
L_TETHER = 100.0                     # m  tether length at this flight point


# ── Helpers ───────────────────────────────────────────────────────────────────

def _tether_dir(elev_rad: float = ELEV_RAD) -> np.ndarray:
    """Unit vector from anchor toward hub at given elevation angle (NED: East = Y)."""
    return np.array([0.0, math.cos(elev_rad), -math.sin(elev_rad)])


def _hub_pos(elev_rad: float = ELEV_RAD, length: float = L_TETHER) -> np.ndarray:
    return length * _tether_dir(elev_rad)


def _R_from_body_z(body_z_world: np.ndarray) -> np.ndarray:
    z = np.asarray(body_z_world, dtype=float)
    z = z / np.linalg.norm(z)
    ref = np.array([0.0, 1.0, 0.0])
    if abs(np.dot(z, ref)) > 0.9:
        ref = np.array([0.0, 0.0, 1.0])
    x = ref - np.dot(ref, z) * z
    x /= np.linalg.norm(x)
    y = np.cross(z, x)
    return np.column_stack([x, y, z])


def _equilibrium_setup():
    """
    Compute the self-consistent equilibrium for steady-state orbit with attitude control.

    Uses the design tether orientation (body_z=[0.851, 0.305, 0.427]) and the
    TensionPI minimum collective (COL_MIN_RAD) as the hold collective — matching
    what the HoldPlanner outputs (thrust=0 → COL_MIN).

    Iterates omega_spin to the autorotation equilibrium at this collective, then
    computes the tether rest length from the expected thrust.

    Returns (coll_rad, omega_spin_eq, R0, pos0, rest_length).
    """
    aero  = create_aero(_rd.default())
    t_dir = _BODY_Z_DESIGN / np.linalg.norm(_BODY_Z_DESIGN)
    R0    = build_orb_frame(t_dir)
    pos0  = L_TETHER * t_dir   # hub at design orientation, radius = tether length

    # Collective = TensionPI minimum (what HoldPlanner thrust=0 gives).
    # The warmup physics is computed at this collective to find the unit-test equilibrium.
    # The stack test uses coll_eq_target (below) for warm_coll_rad — giving TensionPI
    # 0.10 rad of downward headroom during the pumping cycle.
    coll_eq = TensionPI.COLL_MIN_RAD   # -0.28 rad (unit-test equilibrium)

    # Stack-test target collective: 0.10 rad above col_min for PI headroom.
    # At this collective, compute the equilibrium tether tension so the stack test
    # can set tension_out=tension_eq_n.  The TensionPI then operates at coll_eq_target
    # (above col_min) with room to decrease if tension rises.
    coll_eq_target = TensionPI.COLL_MIN_RAD + 0.10   # -0.18 rad

    # Converge omega_spin to autorotation equilibrium at this collective
    k_drive = _ROTOR.K_drive_Nms_m
    k_drag  = _ROTOR.K_drag_Nms2_rad2
    omega_spin_eq = math.sqrt(k_drive * 10.0 / k_drag)   # initial estimate at 10 m/s
    for _ in range(30):
        aero.compute_forces(coll_eq, 0.0, 0.0, R0, np.zeros(3),
                            omega_spin_eq, WIND, t=_T_AERO_OFFSET)
        v_ip = float(aero.last_v_inplane)
        omega_new = math.sqrt(max(1e-6, k_drive * v_ip / k_drag))
        if abs(omega_new - omega_spin_eq) < 1e-4:
            omega_spin_eq = omega_new
            break
        omega_spin_eq = omega_new

    # Estimate tether tension ≈ thrust (for orbit: T_tether ≈ T along tether)
    f = aero.compute_forces(coll_eq, 0.0, 0.0, R0, np.zeros(3),
                            omega_spin_eq, WIND, t=_T_AERO_OFFSET)
    T_est = float(np.dot(f.F_world, t_dir))   # thrust component along tether
    T_t_est = max(T_est, 10.0)                # tether tension ≈ thrust

    k_eff = TetherModel.EA_N / L_TETHER
    ext   = T_t_est / k_eff
    rest  = L_TETHER - max(ext, 0.001)

    # Compute equilibrium tension at the stack-test target collective (coll_eq_target).
    # This is what the stack test's TensionPI should target so it operates at
    # coll_eq_target rather than col_min.
    f_target = aero.compute_forces(coll_eq_target, 0.0, 0.0, R0, np.zeros(3),
                                   omega_spin_eq, WIND, t=_T_AERO_OFFSET)
    T_est_target = float(np.dot(f_target.F_world, t_dir))
    T_gravity_along_tether = MASS * G * math.sin(ELEV_RAD)
    T_tether_target = max(T_est_target - T_gravity_along_tether, 10.0)

    return coll_eq, omega_spin_eq, R0, pos0, rest, coll_eq_target, T_tether_target


_TEL_STRIDE = 20   # log every 20 steps = 20 Hz at 400 Hz


def _run_simulation(steps: int = 4000, warmup_steps: int = 24000):
    """
    Run the steady-state physics for `steps` iterations.

    A warmup pass of `warmup_steps` steps runs first.  The final state of the
    warmup (position, velocity, rotation, orbital omega, spin, tether angle) is
    used as the initial condition for the recorded run.  This means the recorded
    run starts from the system's natural settled state rather than the analytic
    equilibrium estimate — eliminating the initial transient.

    Returns a dict of per-step arrays plus scalars.
    """
    coll_eq, omega_spin_eq, R0, pos0, rest, coll_eq_target, T_tether_target = _equilibrium_setup()

    tension_out = 200.0
    target_alt  = float(-pos0[2])

    # ── Warmup pass ───────────────────────────────────────────────────────────
    runner_wu       = PhysicsRunner.for_warmup(_ROTOR, pos0, R0, rest, coll_eq, omega_spin_eq, WIND)
    alt_ctrl_wu     = AltitudeHoldController.from_pos(pos0, _ROTOR.body_z_slew_rate_rad_s)
    tension_ctrl_wu = TensionPI(setpoint_n=tension_out)
    for _ in range(warmup_steps):
        body_z_eq = alt_ctrl_wu.update(runner_wu.hub_state["pos"], target_alt,
                                        runner_wu.tension_now, MASS, DT)
        coll      = tension_ctrl_wu.update(runner_wu.tension_now, DT)
        runner_wu.step(DT, coll, body_z_eq)

    # ── Settled state ─────────────────────────────────────────────────────────
    s  = runner_wu.hub_state
    ic = SimpleNamespace(
        pos         = s["pos"].copy(),
        vel         = s["vel"].copy(),
        R0          = s["R"].copy(),
        rest_length = rest,
        coll_eq_rad = coll_eq,
        omega_spin  = runner_wu.omega_spin,
    )

    # ── Recorded run ──────────────────────────────────────────────────────────
    runner       = PhysicsRunner(_ROTOR, ic, WIND)
    alt_ctrl     = AltitudeHoldController.from_pos(ic.pos, _ROTOR.body_z_slew_rate_rad_s)
    tension_ctrl = TensionPI(setpoint_n=tension_out)
    tel_rows: list = []

    t_arr     = np.zeros(steps)
    pos_arr   = np.zeros((steps, 3))
    vel_arr   = np.zeros((steps, 3))
    ten_arr   = np.zeros(steps)
    angle_arr = np.zeros(steps)

    for step in range(steps):
        hub = runner.hub_state
        pos = hub["pos"]
        t_arr[step]   = step * DT
        pos_arr[step] = pos
        vel_arr[step] = hub["vel"]
        ten_arr[step] = runner.tension_now

        body_z = hub["R"][:, 2]
        tlen   = np.linalg.norm(pos)
        tdir   = pos / max(tlen, 0.1)
        angle_arr[step] = math.degrees(math.acos(float(np.clip(np.dot(body_z, tdir), -1.0, 1.0))))

        body_z_eq = alt_ctrl.update(pos, target_alt, runner.tension_now, MASS, DT)
        coll      = tension_ctrl.update(runner.tension_now, DT)
        sr        = runner.step(DT, coll, body_z_eq)

        if step % _TEL_STRIDE == 0:
            tel_rows.append(make_tel(
                t_sim          = step * DT,
                hub_state      = hub,
                omega_spin     = runner.omega_spin,
                tether         = runner.tether,
                tension_now    = runner.tension_now,
                collective_rad = coll,
                tilt_lon       = sr["tilt_lon"],
                tilt_lat       = sr["tilt_lat"],
                wind_ned       = WIND,
                body_z_eq      = body_z_eq,
                aero_result    = sr["aero_result"],
                aero_obj       = runner.aero,
                tether_force   = sr["tether_force"],
                tether_moment  = sr["tether_moment"],
                omega_body     = hub["omega"],
                accel_world    = np.zeros(3),
                net_moment     = np.zeros(3),
            ))

    return {
        "coll_deg":      math.degrees(coll_eq),
        "coll_eq":       coll_eq,
        "omega_spin_eq": runner.omega_spin,
        "pos0":          ic.pos,
        "vel0":          ic.vel,
        "R0":            ic.R0,
        "omega0":        s["omega"],
        "rest_length":   rest,
        "tension_eq_n":  T_tether_target,
        "stack_coll_eq": coll_eq_target,
        "t":             t_arr,
        "pos":           pos_arr,
        "vel":           vel_arr,
        "tension":       ten_arr,
        "axle_deg":      angle_arr,
        "tel_rows":      tel_rows,
    }


# ── Test ──────────────────────────────────────────────────────────────────────

def test_steady_flight():
    """Hub stays aloft, tether taut, axle aligned for 10 s from tether equilibrium IC."""
    STEPS     = 4000    # 10 s at 400 Hz
    DRIFT_MAX = 15.0    # m
    AXLE_MAX  = 20.0    # deg

    data = _run_simulation(STEPS)

    if data["tel_rows"]:
        write_csv([TelRow.from_tel(d) for d in data["tel_rows"]],
                  _log.log_dir / "telemetry.csv")

    pos0  = data["pos0"]
    final = data["pos"][-1]
    drift = np.abs(final - pos0)

    _log.write(
        [f"drift_E={drift[1]:.3f}m  drift_Z={drift[2]:.3f}m  steps={STEPS}"],
        f"drift_E={drift[1]:.3f}m  drift_Z={drift[2]:.3f}m",
    )

    failures = []

    if not np.all(np.isfinite(data["pos"])):
        failures.append("NaN/inf in position history")
    if not np.all(np.isfinite(data["vel"])):
        failures.append("NaN/inf in velocity history")

    if drift[1] >= DRIFT_MAX:
        failures.append(
            f"East drift {drift[1]:.2f} m >= {DRIFT_MAX} m "
            f"(coll={data['coll_deg']:.1f} deg)"
        )
    if drift[2] >= DRIFT_MAX:
        failures.append(
            f"Vertical drift {drift[2]:.2f} m >= {DRIFT_MAX} m "
            f"(coll={data['coll_deg']:.1f} deg)"
        )

    slack_steps = np.where(data["tension"] < 0.01)[0]
    if len(slack_steps) > 0:
        failures.append(
            f"tether slack at {len(slack_steps)} steps "
            f"(first at {slack_steps[0]*DT:.2f} s, "
            f"dist={np.linalg.norm(data['pos'][slack_steps[0]]):.2f} m)"
        )

    violations = np.where(data["axle_deg"] > AXLE_MAX)[0]
    if len(violations) > 0:
        failures.append(
            f"axle misaligned > {AXLE_MAX} deg at {len(violations)} steps "
            f"(first at {violations[0]*DT:.2f} s: {data['axle_deg'][violations[0]]:.1f} deg)"
        )

    assert not failures, "\n  ".join(failures)
