#!/usr/bin/env python3
"""
RAWES Simulation Mediator
Bridges ArduPilot SITL <-> Python physics (PhysicsCore) for end-to-end flight simulation.

Architecture:
    ArduPilot SITL  <--UDP 9002/9003-->  mediator.py  <--PhysicsCore-->  dynamics/aero/tether

Data flow (each 400 Hz step):
    1. recv_servos()     — from SITL UDP port 9002
    2. planner step      — free flight only; updates winch + provides traj_cmd
    3. core.step()       — PhysicsCore: aero + tether + RK4 + spin ODE + angular damping
    4. sensor packet     — NED state for ACRO mode (gyro + accel + GPS vel)
    5. send_state()      — to SITL UDP port 9003

Usage:
    python3 mediator.py [options]

Options:
    --sitl-recv-port  PORT     SITL servo recv port  (default: 9002)
    --sitl-send-port  PORT     SITL state send port  (default: 9003)
    --wind-x  FLOAT            Initial wind E [m/s]  (default: 10.0)
    --wind-y  FLOAT            Initial wind N [m/s]  (default: 0.0)
    --wind-z  FLOAT            Initial wind U [m/s]  (default: 0.0)
    --log-level LEVEL          Logging level         (default: INFO)
"""

import argparse
import csv
import logging
import sys
import os

import numpy as np

# Local modules (same directory)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from physics_core    import PhysicsCore
from tether          import TetherModel   # noqa: F401 — re-exported for test callers
from sitl_interface  import SITLInterface
from swashplate      import ardupilot_h3_120_inverse, collective_out_to_rad
from sensor          import make_sensor, SpinSensor
from kinematic       import KinematicStartup, compute_launch_position  # noqa: F401
from winch           import WinchController
from winch_node      import WinchNode, Anemometer
import config as _mcfg
import rotor_definition as _rd
from telemetry_csv import COLUMNS as _TEL_COLUMNS
from mediator_base import install_sigterm_handler, run_lockstep, setup_logging
from mediator_events import MediatorEventLog
from types import SimpleNamespace

# ---------------------------------------------------------------------------
# Configuration defaults
# ---------------------------------------------------------------------------
DT_TARGET    = 1.0 / 400.0    # 400 Hz target loop rate [s]
LOG_INTERVAL = 1.0             # position/attitude log interval [s]
WEIGHT_N     = 294.3           # rotor weight [N] = 30 kg * 9.81 m/s²
I_SPIN_KGMS2 = 10.0            # rotor spin-axis moment of inertia [kg·m²]
OMEGA_SPIN_MIN = 0.5           # minimum spin rate clamp [rad/s]

# GB4008 yaw-damper gain [N·m·s/rad].  Large value → near-perfect yaw lock.
# Reduce to model imperfect GB4008 damping / yaw drift.
_K_YAW_DEFAULT = 100.0

# Spin torque model: Q_net = K_DRIVE * v_inplane − K_DRAG * omega²
#
# The BEM torque integral (Q_positive/Q_negative) cannot model the spin
# equilibrium correctly: because thrust scales as omega², the drive term also
# scales as omega², so drive always exceeds drag and omega runs away without
# limit.  Instead we use a physically-motivated two-term model:
#
#   Q_drive  = K_DRIVE_SPIN × v_inplane   (energy extracted from lateral wind,
#                                           constant for a given wind speed)
#   Q_drag   = K_DRAG_SPIN  × omega²      (profile + induced drag, ∝ rpm²)
#
# These have different omega-dependence, so they balance at a stable
# equilibrium omega_eq = sqrt(K_DRIVE × v_inplane / K_DRAG).
#
# Tuning (at design point: v_wind = 10 m/s → omega_eq = 28 rad/s, λ = 7):
#   K_DRIVE_SPIN × 10  =  K_DRAG_SPIN × 28²
#   Choose K_DRAG_SPIN so that at equilibrium the torque magnitude is ≈ 14 N·m
#   (plausible for a 5 kg, 2.5 m blade rotor):
#       K_DRAG_SPIN  = 14 / 28²  ≈ 0.01786 N·m·s²/rad²
#       K_DRIVE_SPIN = 0.01786 × 28² / 10 = 1.4 N·m·s/m
#
# At v = 20 m/s:  omega_eq = sqrt(1.4 × 20 / 0.01786) ≈ 39.6 rad/s  (higher wind → faster spin)
K_DRIVE_SPIN = 1.4      # N·m·s/m   (autorotation drive per unit in-plane wind speed)
K_DRAG_SPIN  = 0.01786  # N·m·s²/rad²  (profile drag coefficient)

# Default initial state — warmup-settled equilibrium from test_steady_flight.py.
# 50 m tether at ~30° elevation (ENU), body Z aligned with tether direction.
# Generated by running: pytest simulation/tests/unit/test_steady_flight.py
# Initial state defaults live in config.py (DEFAULTS dict) — single source of truth.


# compute_launch_position is imported from kinematic.py (see imports above).
# It is re-exported here so existing callers (test_startup_trajectory.py) continue
# to work with:  from mediator import compute_launch_position


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
def _parse_args():
    parser = argparse.ArgumentParser(
        description="RAWES Simulation Mediator — bridges ArduPilot SITL and Python RK4 dynamics",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--config", default=None,
                        help="Path to a JSON configuration file.  All physics and control "
                             "parameters live here.  See _CONFIG_DEFAULTS in mediator.py for "
                             "the full schema and default values.  Missing keys fall back to "
                             "defaults.")
    parser.add_argument("--run-id", type=int, default=None,
                        help="Integer run ID shared across all log files for this test run.")
    parser.add_argument("--sitl-recv-port", type=int, default=9002,
                        help="UDP port to listen on for SITL servo data")
    parser.add_argument("--sitl-send-port", type=int, default=9003,
                        help="UDP port to send physics state to SITL")
    parser.add_argument("--log-level", default="INFO",
                        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
                        help="Logging verbosity level")
    parser.add_argument("--telemetry-log", default=None,
                        help="Path for per-step CSV telemetry log")
    parser.add_argument("--events-log", default=None,
                        help="Path for structured JSONL event log")
    parser.add_argument("--winch-cmd-port", type=int, default=0,
                        help="UDP port for remote winch control (0 = disabled). "
                             "When set, the mediator listens for {target_length, "
                             "target_tension} JSON datagrams from the test process "
                             "and sends back {tension_n, rest_length, hub_alt_m}.")
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Main mediator loop
# ---------------------------------------------------------------------------
def run_mediator(args, trajectory=None):
    """
    Run the mediator loop.

    Parameters
    ----------
    args       : argparse.Namespace — CLI arguments (ports, log level, etc.)
    trajectory : TrajectoryController or None
        Pre-constructed trajectory controller.  When provided, the mediator
        uses it directly.  When None (default), a controller is built from
        the ``cfg["trajectory"]`` section of the config file — this is the
        standard path when running as a subprocess launched by stack tests.
        Callers that want full control pass a pre-built object; the config
        section is only needed for subprocess/CLI use.
    """
    import time as _time_mod
    log = logging.getLogger("mediator")
    is_stopped = install_sigterm_handler()
    ev  = MediatorEventLog(getattr(args, "events_log", None))
    ev.open()

    cfg = _mcfg.load(getattr(args, "config", None))

    # Emit a run-ID so post-run analysis can verify all log files belong to
    # the same test run.  Format: RUN_ID=<integer epoch seconds>.
    # Authoritative source: conftest.py generates once and passes via --run-id.
    # When run standalone (no --run-id), generate locally as fallback.
    _run_id = args.run_id if args.run_id is not None else int(_time_mod.time())
    wind_world = np.array(cfg["wind"])
    ev.write("startup", t_sim=0.0, run_id=_run_id, wind_ned=wind_world.tolist())

    # -- Instantiate subsystems -----------------------------------------------
    # Mass comes from beaupoil_2026.yaml (currently 5.0 kg hardware mass).
    # I_spin=0: do NOT include rotor gyroscopic coupling in the orbital dynamics.
    # The lumped single-body model uses ArduPilot's cyclic commands directly as
    # tilting moments (no blade flapping model).  The 90° gyroscopic precession
    # that a real spinning rotor would produce is already compensated by the
    # swashplate phase angle in a real helicopter; adding it here without the
    # corresponding phase compensation would cause ArduPilot's attitude
    # controller to tilt the disk in the wrong direction.
    # ── Initial state ──────────────────────────────────────────────────────────
    _pos0_arr        = np.array(cfg["pos0"],     dtype=float)
    _vel0_arr        = np.array(cfg["vel0"],     dtype=float)
    _omega_spin_init = float(cfg["omega_spin"])
    _R0 = np.array(cfg["R0"], dtype=float).reshape(3, 3)

    # -- Kinematic startup trajectory -----------------------------------------
    # Only "linear" is supported: constant vel0 from launch_pos, optional ramp
    # to zero.  With dual GPS (EK3_SRC1_YAW=2) yaw is known from the first fix;
    # no circular motion or EKFGSF convergence is needed.
    _kin_duration    = max(0.0, float(cfg["startup_damp_seconds"]))


    _startup = KinematicStartup(
        target_pos = _pos0_arr,
        target_vel = _vel0_arr,
        duration   = _kin_duration,
        ramp_s     = float(cfg["kinematic_vel_ramp_s"]),
        R0         = _R0,
    )
    if _startup.duration > 0.0:
        ev.write("kinematic_config", t_sim=0.0,
                 traj_type="linear",
                 total_s=round(_startup.duration, 1),
                 ramp_s=round(_startup.ramp_s, 1),
                 launch_pos=[round(v, 3) for v in _startup.launch_pos],
                 vel=_vel0_arr.tolist())
    _dyn_pos0 = _startup.launch_pos
    _dyn_vel0 = _vel0_arr

    rotor  = _rd.load(cfg["rotor_definition"])
    log.info("Rotor: %s", rotor.summary())
    issues = rotor.validate()
    for issue in issues:
        if issue.level == "ERROR":
            log.error("Rotor validation: %s", issue)
        elif issue.level == "WARNING":
            log.warning("Rotor validation: %s", issue)

    # Shadow module-level constants with rotor-definition values
    K_DRIVE_SPIN  = rotor.K_drive_Nms_m
    K_DRAG_SPIN   = rotor.K_drag_Nms2_rad2
    I_SPIN_KGMS2  = rotor.I_ode_kgm2
    OMEGA_SPIN_MIN = rotor.omega_min_rad_s

    # Collective denormalisation range (must precede _ic which uses _col_min_rad)
    _traj_cfg    = cfg["trajectory"]["deschutter"]
    _col_min_rad = float(_traj_cfg["col_min_rad"])
    _col_max_rad = float(_traj_cfg["col_max_rad"])

    sitl = SITLInterface(
        recv_port=args.sitl_recv_port,
    )
    _ic = SimpleNamespace(
        pos        = _dyn_pos0,
        vel        = _dyn_vel0,
        R0         = _R0,
        rest_length= float(cfg["rest_length"]),
        coll_eq_rad= _col_min_rad,
        omega_spin = _omega_spin_init,
    )
    core = PhysicsCore(
        rotor, _ic, wind_world,
        base_k_ang         = float(cfg["base_k_ang"]),
        k_yaw              = float(cfg.get("k_yaw", _K_YAW_DEFAULT)),
        kinematic          = _startup,
        startup_damp_k_ang = float(cfg["startup_damp_k_ang"]),
        lock_orientation   = bool(cfg["lock_orientation"]),
        z_floor            = -1.0,
    )
    sensor_sim = make_sensor(
        home_ned_z = float(_pos0_arr[2]),
    )
    spin_sensor = SpinSensor(
        sigma    = float(cfg["spin_sensor_sigma"]),
        K_drive  = K_DRIVE_SPIN,
        K_drag   = K_DRAG_SPIN,
    )
    ev.write("config", t_sim=0.0,
             spin_sensor_sigma=round(spin_sensor._sigma, 3),
             tether_EA_kN=round(core.tether.EA / 1000),
             tether_rest_length_m=round(core.tether.rest_length, 1),
             tether_damping=round(core.tether.damping, 1),
             tether_break_load_N=round(core.tether.BREAK_LOAD_N))

    # -- Connect ---------------------------------------------------------------
    log.info("Binding SITL UDP sockets...")
    sitl.bind()
    log.info("Python RigidBodyDynamics ready. Starting main loop.")

    # -- State ----------------------------------------------------------------
    step            = 0
    last_log_time   = -LOG_INTERVAL       # ensure immediate first log
    _t_step0        = None                # sim time of first step_fn call

    s1 = s2 = s3       = 0.0           # servo values
    _traj_cmd          = {"phase": "", "tension_setpoint": 0.0}  # last trajectory command
    _logged_transition = False         # one-shot: kinematic → free-flight transition log
    _tel_note          = ""            # single-frame event marker written to telemetry CSV; cleared after write
    _prev_phase        = ""            # detect phase changes for tel note
    ev.write("config", t_sim=0.0,
             startup_damp_T_s=round(_startup.duration, 1),
             startup_damp_ramp_s=round(_startup.ramp_s, 1),
             startup_damp_k_ang=round(float(cfg["startup_damp_k_ang"])))

    # -- Telemetry CSV --------------------------------------------------------
    _telemetry_file   = None
    _telemetry_writer = None
    if args.telemetry_log:
        _telemetry_file = open(args.telemetry_log, "w", newline="", encoding="utf-8")  # noqa: WPS515
        _telemetry_writer = csv.DictWriter(_telemetry_file, fieldnames=_TEL_COLUMNS)
        _telemetry_writer.writeheader()
        log.info("Telemetry logging -> %s", args.telemetry_log)

    # -- WinchNode (separate MAVLink node, co-located physically with anchor) --
    # Encapsulates WinchController + Anemometer.  The planner communicates
    # with this node ONLY through get_telemetry() and receive_command().
    # The mediator calls update_sensors() to feed physics outputs in.
    _winch_node = WinchNode(
        winch=WinchController(
            rest_length     = float(cfg["rest_length"]),
            kp_tension      = float(cfg["winch_kp_tension"]),
            v_max_out       = float(cfg["winch_v_max_out"]),
            v_max_in        = float(cfg["winch_v_max_in"]),
            accel_limit_ms2 = float(cfg["winch_accel_limit_ms2"]),
            min_length      = float(cfg["winch_min_length"]),
        ),
        anemometer=Anemometer(height_m=3.0),
    )
    _winch_node.update_sensors(0.0, wind_world)   # prime anemometer before planner init

    # -- Trajectory planner (ground station) ---------------------------------
    # Caller supplies a pre-built planner, or one is built from cfg["trajectory"].
    # Wind seed comes from the WinchNode anemometer -- NOT from wind_world directly.
    _pc_telemetry: dict = _winch_node.get_telemetry()
    if trajectory is not None:
        _trajectory = trajectory
    else:
        _trajectory = _mcfg.make_trajectory(
            cfg, wind_ned=_pc_telemetry["wind_ned"])
    ev.write("config", t_sim=0.0, trajectory=type(_trajectory).__name__)

    # -- Winch command socket (pumping mode: test process controls planner) ---
    # When --winch-cmd-port is set the test process runs PumpingGroundController
    # and sends winch commands here.  The mediator owns WinchController physics;
    # the test owns phase management and NVF delivery to Lua via MAVLink GCS.
    #
    # Protocol (UDP JSON, all on one socket):
    #   test  -> mediator: {"target_length": L, "target_tension": T}
    #   mediator -> test:  {"tension_n": T, "rest_length": L, "hub_alt_m": H}
    #
    # State is sent every ~10 Hz (every DT_WINCH_SEND steps).  Commands are
    # received non-blocking every step so they are applied within one lockstep
    # cycle (~2.5 ms latency).
    import socket as _socket_mod
    import json   as _json_mod
    _winch_cmd_port = int(cfg.get("winch_cmd_port", 0)) or getattr(args, "winch_cmd_port", 0)
    _winch_sock     = None
    _winch_peer     = None   # (host, port) of the test process — learned on first recv
    _winch_send_ctr = 0
    DT_WINCH_SEND   = 40    # send state every 40 steps ≈ 10 Hz at 400 Hz loop

    if _winch_cmd_port > 0:
        _winch_sock = _socket_mod.socket(_socket_mod.AF_INET, _socket_mod.SOCK_DGRAM)
        _winch_sock.bind(("127.0.0.1", _winch_cmd_port))
        _winch_sock.setblocking(False)
        log.info("Winch command socket listening on 127.0.0.1:%d", _winch_cmd_port)

    # -- Mode_RAWES inner loops -----------------------------------------------

    log.info("Entering main loop at %.0f Hz target.", 1.0 / DT_TARGET)

    # -- Step function (one lockstep iteration) --------------------------------
    # Called by run_lockstep once per servo packet. Closes over all subsystems
    # and mutable state declared above. Returns the state dict for send_state().

    def step_fn(servos, t_sim):
        nonlocal step, last_log_time, _t_step0
        nonlocal s1, s2, s3, _traj_cmd, _logged_transition
        nonlocal _tel_note, _prev_phase
        nonlocal _winch_peer, _winch_send_ctr
        if _t_step0 is None:
            _t_step0 = t_sim
        _dt = sitl.dt()

        # Pre-compute kinematic phase from core.t_sim so it matches what
        # PhysicsCore uses internally — gates planner + tether sensor update.
        _damp_alpha = _startup.damp_alpha(core.t_sim)

        # ── Ground-station planner + WinchNode (free flight only) ────────
        if _damp_alpha == 0.0:
            _ti_prev = core.tether._last_info
            if _ti_prev.get("tension", 0) > 0.8 * core.tether.BREAK_LOAD_N:
                log.warning(
                    "t=%.1f TETHER TENSION %.0f N is >80%% of break load (%.0f N)!",
                    core.t_sim, _ti_prev["tension"], core.tether.BREAK_LOAD_N,
                )
            _winch_node.update_sensors(core.tension_now, wind_world)
            _pc_telemetry = _winch_node.get_telemetry()

            # ── Winch command socket: receive set_target commands from test ──
            _socket_phase = None  # ground-planner phase label (applied after trajectory.step)
            if _winch_sock is not None:
                try:
                    _data, _addr = _winch_sock.recvfrom(256)
                    _cmd = _json_mod.loads(_data)
                    _winch_node.set_target(
                        float(_cmd["target_length"]),
                        float(_cmd["target_tension"]),
                    )
                    if "phase" in _cmd:
                        _socket_phase = _cmd["phase"]
                    _winch_peer = _addr
                except BlockingIOError:
                    pass

                # Send winch state back to test at ~10 Hz
                _winch_send_ctr += 1
                if _winch_send_ctr >= DT_WINCH_SEND and _winch_peer is not None:
                    _winch_send_ctr = 0
                    _state_bytes = _json_mod.dumps({
                        "tension_n":   core.tension_now,
                        "rest_length": _winch_node.rest_length,
                        "hub_alt_m":   float(-core.hub_state["pos"][2]),
                    }).encode()
                    _winch_sock.sendto(_state_bytes, _winch_peer)

            _state_pkt = {
                "pos_ned":    core.hub_state["pos"],
                "vel_ned":    core.hub_state["vel"],
                "omega_spin": spin_sensor.measure(core.omega_spin),
                "body_z":     core.hub_state["R"][:, 2],
            }
            _traj_cmd = _trajectory.step(
                _state_pkt, _dt,
                tension_n       = _pc_telemetry["tension_n"],
                tether_length_m = _pc_telemetry["tether_length_m"],
            )
            # Mirror the ground planner phase AFTER trajectory.step() so the
            # HoldPlanner's "hold" label doesn't overwrite the socket phase.
            if _socket_phase is not None:
                _traj_cmd = dict(_traj_cmd)
                _traj_cmd["phase"] = _socket_phase
            _winch_node.receive_command(_traj_cmd["winch_speed_ms"], _dt)

        # ── Physics step ──────────────────────────────────────────────────
        prev_vel = core.hub_state["vel"].copy()

        s1 = float(servos[0])
        s2 = float(servos[1])
        s3 = float(servos[2])
        collective_out, roll_norm, pitch_norm = ardupilot_h3_120_inverse(s1, s2, s3)
        _tilt_lat = roll_norm
        _tilt_lon = pitch_norm
        collective_rad = float(np.clip(
            collective_out_to_rad(collective_out, _col_min_rad, _col_max_rad),
            _col_min_rad, _col_max_rad,
        ))
        if _damp_alpha == 0.0:
            core.tether.rest_length = _winch_node.rest_length
        result = core.step(_dt, collective_rad, _tilt_lon, _tilt_lat)

        # ── Unpack physics results ────────────────────────────────────────
        hub_state     = result["hub_state"]
        tether_force  = result["tether_force"]
        tether_moment = result["tether_moment"]
        tilt_lon      = result["tilt_lon"]
        tilt_lat      = result["tilt_lat"]
        aero_result   = result["aero_result"]

        F_net  = aero_result.F_world + tether_force
        M_net  = aero_result.M_orbital + tether_moment
        forces = np.concatenate([F_net, M_net + aero_result.M_spin])

        disk_normal = hub_state["R"][:, 2]
        T_est = max(0.0, float(np.dot(F_net, disk_normal)))

        # ── Kinematic → free-flight transition (one-shot log) ────────────
        if _damp_alpha == 0.0 and not _logged_transition:
            _logged_transition = True
            _tel_note = "kinematic_exit"
            _ti = core.tether._last_info
            ev.write("kinematic_exit", t_sim=core.t_sim,
                     pos_ned=[round(v, 4) for v in hub_state["pos"].tolist()],
                     vel_ned=[round(v, 4) for v in hub_state["vel"].tolist()],
                     body_z=[round(v, 4) for v in hub_state["R"][:, 2].tolist()],
                     omega=[round(v, 4) for v in hub_state["omega"].tolist()],
                     tether_length_m=round(_ti.get("length", 0.0), 4),
                     tether_tension_n=round(_ti.get("tension", 0.0), 2),
                     tether_slack=bool(_ti.get("slack", True)),
                     T_aero_n=round(T_est, 2),
                     omega_spin_rad_s=round(core.omega_spin, 3),
                     collective_rad=round(collective_rad, 4))

        # ── Sensor packet ─────────────────────────────────────────────────
        new_vel = hub_state["vel"]
        accel_world = (new_vel - prev_vel) / _dt

        sensor_data = sensor_sim.compute(
            pos_ned         = hub_state["pos"],
            vel_ned         = hub_state["vel"],
            R_hub           = hub_state["R"],
            omega_body      = hub_state["omega"],
            accel_world_ned = accel_world,
            dt              = _dt,
        )

        # ── Telemetry CSV ─────────────────────────────────────────────────
        if _telemetry_writer is not None:
            _rpy = sensor_data["rpy"]
            _ti  = core.tether._last_info
            _cur_phase = _traj_cmd.get("phase", "")
            if _cur_phase and _cur_phase != _prev_phase and not _tel_note:
                _tel_note = f"phase_{_cur_phase.replace('-', '_')}_start"
            _prev_phase = _cur_phase
            _telemetry_writer.writerow({
                "t_sim":           core.t_sim,
                "phase":           _cur_phase,
                "note":            _tel_note,
                "damp_alpha":      _damp_alpha,
                "pos_x":           hub_state["pos"][0],
                "pos_y":           hub_state["pos"][1],
                "pos_z":           hub_state["pos"][2],
                "vel_x":           hub_state["vel"][0],
                "vel_y":           hub_state["vel"][1],
                "vel_z":           hub_state["vel"][2],
                "omega_x":         hub_state["omega"][0],
                "omega_y":         hub_state["omega"][1],
                "omega_z":         hub_state["omega"][2],
                "accel_x":         accel_world[0],
                "accel_y":         accel_world[1],
                "accel_z":         accel_world[2],
                "omega_rotor":     core.omega_spin,
                "tether_length":   _ti.get("length",    0.0),
                "tether_extension":_ti.get("extension", 0.0),
                "tether_tension":  _ti.get("tension",   0.0),
                "tether_rest_length": core.tether.rest_length,
                "tether_slack":    1 if _ti.get("slack", True) else 0,
                "tether_fx":       tether_force[0],
                "tether_fy":       tether_force[1],
                "tether_fz":       tether_force[2],
                "aero_fx":         aero_result.F_world[0],
                "aero_fy":         aero_result.F_world[1],
                "aero_fz":         aero_result.F_world[2],
                "aero_mx":         aero_result.M_orbital[0],
                "aero_my":         aero_result.M_orbital[1],
                "aero_mz":         aero_result.M_orbital[2],
                "tether_mx":       tether_moment[0],
                "tether_my":       tether_moment[1],
                "tether_mz":       tether_moment[2],
                "collective_rad":  collective_rad,
                "collective_norm": collective_out,
                "tilt_lon":        tilt_lon,
                "tilt_lat":        tilt_lat,
                "tension_setpoint":            _traj_cmd.get("tension_setpoint", 0.0),
                "collective_from_tension_ctrl": collective_rad,
                "aero_T":          core.aero.last_T,
                "aero_v_axial":    core.aero.last_v_axial,
                "aero_v_inplane":  core.aero.last_v_inplane,
                "aero_v_i":        core.aero.last_v_i,
                "aero_Q_drag":     core.aero.last_Q_drag,
                "aero_Q_drive":    core.aero.last_Q_drive,
                "F_x":             forces[0],
                "F_y":             forces[1],
                "F_z":             forces[2],
                "M_x":             forces[3],
                "M_y":             forces[4],
                "M_z":             forces[5],
                "rpy_roll":        _rpy[0],
                "rpy_pitch":       _rpy[1],
                "rpy_yaw":         _rpy[2],
                "orb_yaw_rad":     sensor_data.get("orb_yaw_rad", 0.0),
                "v_horiz_ms":      sensor_data.get("v_horiz_ms",  0.0),
                "sens_vel_n":      sensor_data["vel_ned"][0],
                "sens_vel_e":      sensor_data["vel_ned"][1],
                "sens_vel_d":      sensor_data["vel_ned"][2],
                "sens_accel_x":    sensor_data["accel_body"][0],
                "sens_accel_y":    sensor_data["accel_body"][1],
                "sens_accel_z":    sensor_data["accel_body"][2],
                "sens_gyro_x":     sensor_data["gyro_body"][0],
                "sens_gyro_y":     sensor_data["gyro_body"][1],
                "sens_gyro_z":     sensor_data["gyro_body"][2],
                "vel_heading_deg": float(np.degrees(
                    np.arctan2(sensor_data["vel_ned"][1], sensor_data["vel_ned"][0]))),
                "heading_gap_deg": float(
                    (np.degrees(sensor_data.get("orb_yaw_rad", 0.0))
                     - np.degrees(np.arctan2(
                         sensor_data["vel_ned"][1], sensor_data["vel_ned"][0]))
                     + 180.0) % 360.0 - 180.0),
                "servo_s1_us":     float(sitl.last_pwm_raw[0]),
                "servo_s2_us":     float(sitl.last_pwm_raw[1]),
                "servo_s3_us":     float(sitl.last_pwm_raw[2]),
                "servo4_us":       float(sitl.last_pwm_raw[3]),
                "wind_x":          wind_world[0],
                "wind_y":          wind_world[1],
                "wind_z":          wind_world[2],
                "r00": float(hub_state["R"][0, 0]),
                "r01": float(hub_state["R"][0, 1]),
                "r02": float(hub_state["R"][0, 2]),
                "r10": float(hub_state["R"][1, 0]),
                "r11": float(hub_state["R"][1, 1]),
                "r12": float(hub_state["R"][1, 2]),
                "r20": float(hub_state["R"][2, 0]),
                "r21": float(hub_state["R"][2, 1]),
                "r22": float(hub_state["R"][2, 2]),
            })
            _tel_note = ""

        # ── Return sensor packet ──────────────────────────────────────────
        # Delay GPS velocity for the first 2 sim-seconds so EKFGSF can
        # run alignTilt() before fuseVelData() is called.
        _gps_ready = (t_sim - _t_step0) >= 2.0
        step += 1
        return dict(
            pos_ned    = sensor_data["pos_ned"],
            vel_ned    = sensor_data["vel_ned"] if _gps_ready else np.zeros(3),
            rpy_rad    = sensor_data["rpy"],
            accel_body = sensor_data["accel_body"],
            gyro_body  = sensor_data["gyro_body"],
            rpm_rad_s  = core.omega_spin,
        )

    # -- Run lockstep ---------------------------------------------------------
    try:
        run_lockstep(sitl, step_fn, is_stopped, log=log, ev=ev)
    except KeyboardInterrupt:
        log.info("KeyboardInterrupt received — shutting down.")
    except Exception as exc:
        log.exception("Fatal error in main loop: %s", exc)
        raise
    finally:
        # -- Graceful shutdown ------------------------------------------------
        ev.write("shutdown", t_sim=sitl.sim_now(),
                 step=step,
                 pos_ned=[round(v, 3) for v in core.hub_state["pos"].tolist()],
                 vel_ned=[round(v, 3) for v in core.hub_state["vel"].tolist()],
                 omega_spin_rad_s=round(core.omega_spin, 2))
        ev.close()

        if _telemetry_file is not None:
            try:
                _telemetry_file.flush()
                _telemetry_file.close()
                log.info("Telemetry log closed.")
            except Exception:
                pass

        log.info("Closing connections ...")
        try:
            sitl.close()
        except Exception:
            pass
        log.info("Mediator stopped.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    args = _parse_args()
    setup_logging(args.log_level)
    run_mediator(args)


if __name__ == "__main__":
    main()
