#!/usr/bin/env python3
"""
RAWES Simulation Mediator
Bridges ArduPilot SITL <-> Python RK4 dynamics for end-to-end flight simulation.

Architecture:
    ArduPilot SITL  <--UDP 9002/9003-->  mediator.py  <--function call-->  dynamics.py (RK4)

Data flow (each 400 Hz step):
    1. recv_servos()     — non-blocking, from SITL UDP port 9002
    2. swashplate mix    — servo PWM -> collective + cyclic tilt
                          OR compute_swashplate_from_state() if --internal-controller
    3. aero.compute()    — BEM forces in world (ENU) frame
    4. tether.compute()  — tension-only tether force added to wrench
    5. dynamics.step()   — RK4 6-DOF integration (pure Python, gravity internal)
    6. sensor packet     — minimal NED state for ACRO mode (gyro + constant gravity)
    7. send_state()      — to SITL UDP port 9003

Usage:
    python3 mediator.py [options]

Options:
    --sitl-recv-port  PORT     SITL servo recv port  (default: 9002)
    --sitl-send-port  PORT     SITL state send port  (default: 9003)
    --wind-x  FLOAT            Initial wind E [m/s]  (default: 10.0)
    --wind-y  FLOAT            Initial wind N [m/s]  (default: 0.0)
    --wind-z  FLOAT            Initial wind U [m/s]  (default: 0.0)
    --log-level LEVEL          Logging level         (default: INFO)
"""

import argparse
import csv
import logging
import math
import sys
import time
import os

import numpy as np

# Local modules (same directory)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dynamics        import RigidBodyDynamics
from sitl_interface  import SITLInterface
from swashplate      import h3_inverse_mix, collective_to_pitch, cyclic_to_blade_pitches, pwm_to_normalized
from aero            import SkewedWakeBEM
from tether          import TetherModel
from frames          import build_orb_frame
from sensor          import make_sensor, SpinSensor
from controller      import compute_swashplate_from_state, OrbitTracker
from winch           import WinchController
from winch_node      import WinchNode, Anemometer
from planner         import HoldPlanner, DeschutterPlanner, quat_apply, quat_is_identity
import config as _mcfg
import rotor_definition as _rd

# ---------------------------------------------------------------------------
# Configuration defaults
# ---------------------------------------------------------------------------
DT_TARGET    = 1.0 / 400.0    # 400 Hz target loop rate [s]
LOG_INTERVAL = 1.0             # position/attitude log interval [s]
WEIGHT_N     = 294.3           # rotor weight [N] = 30 kg * 9.81 m/s²
I_SPIN_KGMS2 = 10.0            # rotor spin-axis moment of inertia [kg·m²]
OMEGA_SPIN_MIN = 0.5           # minimum spin rate clamp [rad/s]

# Spin torque model: Q_net = K_DRIVE * v_inplane − K_DRAG * omega²
#
# The BEM torque integral (Q_positive/Q_negative) cannot model the spin
# equilibrium correctly: because thrust scales as omega², the drive term also
# scales as omega², so drive always exceeds drag and omega runs away without
# limit.  Instead we use a physically-motivated two-term model:
#
#   Q_drive  = K_DRIVE_SPIN × v_inplane   (energy extracted from lateral wind,
#                                           constant for a given wind speed)
#   Q_drag   = K_DRAG_SPIN  × omega²      (profile + induced drag, ∝ rpm²)
#
# These have different omega-dependence, so they balance at a stable
# equilibrium omega_eq = sqrt(K_DRIVE × v_inplane / K_DRAG).
#
# Tuning (at design point: v_wind = 10 m/s → omega_eq = 28 rad/s, λ = 7):
#   K_DRIVE_SPIN × 10  =  K_DRAG_SPIN × 28²
#   Choose K_DRAG_SPIN so that at equilibrium the torque magnitude is ≈ 14 N·m
#   (plausible for a 5 kg, 2.5 m blade rotor):
#       K_DRAG_SPIN  = 14 / 28²  ≈ 0.01786 N·m·s²/rad²
#       K_DRIVE_SPIN = 0.01786 × 28² / 10 = 1.4 N·m·s/m
#
# At v = 20 m/s:  omega_eq = sqrt(1.4 × 20 / 0.01786) ≈ 39.6 rad/s  (higher wind → faster spin)
K_DRIVE_SPIN = 1.4      # N·m·s/m   (autorotation drive per unit in-plane wind speed)
K_DRAG_SPIN  = 0.01786  # N·m·s²/rad²  (profile drag coefficient)

# Default initial state — warmup-settled equilibrium from test_steady_flight.py.
# 50 m tether at ~30° elevation (ENU), body Z aligned with tether direction.
# Generated by running: pytest simulation/tests/unit/test_steady_flight.py
# Initial state defaults live in config.py (DEFAULTS dict) — single source of truth.


# ---------------------------------------------------------------------------
# Startup trajectory helpers
# ---------------------------------------------------------------------------

def compute_launch_position(target_pos, target_vel, damp_seconds: float,
                            ramp_s: float = 0.0):
    """Compute the starting position for a kinematic startup trajectory.

    The hub travels at constant velocity vel from launch_pos, arriving at
    target_pos at t=damp_seconds.  If ramp_s > 0, the velocity is linearly
    tapered to zero over the last ramp_s seconds so the hub enters free flight
    at rest.  launch_pos is adjusted so the hub still reaches target_pos at
    t=damp_seconds despite the reduced average velocity during the ramp.

    Velocity profile:
        t in [0,  T-ramp_s]:  v(t) = target_vel        (constant)
        t in [T-ramp_s, T]:   v(t) = target_vel * (T-t)/ramp_s  (linear → 0)

    Position at t=T with ramp:
        launch_pos + target_vel*(T-ramp_s) + target_vel*ramp_s/2 = target_pos
        → launch_pos = target_pos − target_vel*(T − ramp_s/2)

    Without ramp (ramp_s=0):
        launch_pos = target_pos − target_vel*T   (original formula)

    Benefits:
    - Non-zero velocity during [0, T-ramp_s] → EKF derives yaw heading early
    - Zero acceleration → IMU sees only gravity (cleaner EKF signal)
    - Zero entry velocity → no kinetic kick at free-flight start (stable TensionPI)

    Returns
    -------
    launch_pos : np.ndarray shape (3,)
    """
    target_pos = np.asarray(target_pos, dtype=float)
    target_vel = np.asarray(target_vel, dtype=float)
    ramp_s = float(np.clip(ramp_s, 0.0, damp_seconds))
    launch_pos = target_pos - target_vel * (damp_seconds - ramp_s / 2.0)
    return launch_pos


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
def _parse_args():
    parser = argparse.ArgumentParser(
        description="RAWES Simulation Mediator — bridges ArduPilot SITL and Python RK4 dynamics",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--config", default=None,
                        help="Path to a JSON configuration file.  All physics and control "
                             "parameters live here.  See _CONFIG_DEFAULTS in mediator.py for "
                             "the full schema and default values.  Missing keys fall back to "
                             "defaults.")
    parser.add_argument("--run-id", type=int, default=None,
                        help="Integer run ID shared across all log files for this test run.")
    parser.add_argument("--sitl-recv-port", type=int, default=9002,
                        help="UDP port to listen on for SITL servo data")
    parser.add_argument("--sitl-send-port", type=int, default=9003,
                        help="UDP port to send physics state to SITL")
    parser.add_argument("--log-level", default="INFO",
                        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
                        help="Logging verbosity level")
    parser.add_argument("--telemetry-log", default=None,
                        help="Path for per-step CSV telemetry log")
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Main mediator loop
# ---------------------------------------------------------------------------
def run_mediator(args, trajectory=None):
    """
    Run the mediator loop.

    Parameters
    ----------
    args       : argparse.Namespace — CLI arguments (ports, log level, etc.)
    trajectory : TrajectoryController or None
        Pre-constructed trajectory controller.  When provided, the mediator
        uses it directly.  When None (default), a controller is built from
        the ``cfg["trajectory"]`` section of the config file — this is the
        standard path when running as a subprocess launched by stack tests.
        Callers that want full control pass a pre-built object; the config
        section is only needed for subprocess/CLI use.
    """
    import time as _time_mod
    log = logging.getLogger("mediator")

    cfg = _mcfg.load(getattr(args, "config", None))

    # Emit a run-ID so post-run analysis can verify all log files belong to
    # the same test run.  Format: RUN_ID=<integer epoch seconds>.
    # Authoritative source: conftest.py generates once and passes via --run-id.
    # When run standalone (no --run-id), generate locally as fallback.
    _run_id = args.run_id if args.run_id is not None else int(_time_mod.time())
    log.info("RUN_ID=%d", _run_id)

    wind_world = np.array(cfg["wind"])
    log.info("Wind vector (NED): %s m/s", wind_world)

    # -- Instantiate subsystems -----------------------------------------------
    # Mass 30 kg: the blade geometry (4 × 2 m, chord 0.15 m) was scaled from
    # the De Schutter (2018) 40 kg reference design.  At the design tip-speed
    # ratio (λ = 7, v_wind = 10 m/s → ω = 28 rad/s) the BEM model produces
    # ~300 N of thrust at neutral collective — consistent with a ~30 kg rotor
    # hovering near its natural autorotation equilibrium.  Using 5 kg (actual
    # hardware mass) causes 6× over-thrust and makes the altitude controller
    # saturate.  TODO: either retune the blade geometry to the actual mass, or
    # verify the hardware mass is correct (5 kg seems very light for this blade
    # area and tip speed).
    # I_spin=0: do NOT include rotor gyroscopic coupling in the orbital dynamics.
    # The lumped single-body model uses ArduPilot's cyclic commands directly as
    # tilting moments (no blade flapping model).  The 90° gyroscopic precession
    # that a real spinning rotor would produce is already compensated by the
    # swashplate phase angle in a real helicopter; adding it here without the
    # corresponding phase compensation would cause ArduPilot's attitude
    # controller to tilt the disk in the wrong direction.
    # ── Initial state ──────────────────────────────────────────────────────────
    _pos0_arr        = np.array(cfg["pos0"],     dtype=float)
    _vel0_arr        = np.array(cfg["vel0"],     dtype=float)
    _omega_spin_init = float(cfg["omega_spin"])
    _bz_raw          = np.array(cfg["body_z"],   dtype=float)
    _bz = _bz_raw / np.linalg.norm(_bz_raw)

    # Build _R0: body-X is the East-projection of _bz.
    _R0 = build_orb_frame(_bz)

    # -- Kinematic startup trajectory -----------------------------------------
    # Instead of force-based damping (which zeroes velocity and leaves the hub
    # in a non-physical hover state), we compute a "launch position" from which
    # constant acceleration smoothly carries the hub to (_pos0, _vel0) at t=T.
    #
    #   launch_pos = _pos0 − _vel0 × T
    #
    # During the startup window the hub state is overridden directly (no physics
    # integration for translation); physics takes over at t=T with the hub
    # exactly at the equilibrium position and velocity.
    _startup_damp_T  = max(0.0, float(cfg["startup_damp_seconds"]))
    _vel_ramp_s      = float(np.clip(cfg["kinematic_vel_ramp_s"], 0.0, _startup_damp_T))
    _t_ramp_start    = _startup_damp_T - _vel_ramp_s   # time when vel ramp begins
    if _startup_damp_T > 0.0:
        _launch_pos = compute_launch_position(
            _pos0_arr, _vel0_arr, _startup_damp_T, _vel_ramp_s)
        log.info(
            "Kinematic startup: T=%.0fs  ramp=%.0fs  "
            "launch_pos=[%.3f, %.3f, %.3f]  vel=[%.5f, %.5f, %.5f] m/s",
            _startup_damp_T, _vel_ramp_s, *_launch_pos, *_vel0_arr,
        )
        _dyn_pos0 = _launch_pos
        _dyn_vel0 = _vel0_arr
    else:
        _launch_pos   = _pos0_arr.copy()
        _dyn_pos0     = _pos0_arr
        _dyn_vel0     = _vel0_arr

    rotor  = _rd.load(cfg["rotor_definition"])
    log.info("Rotor: %s", rotor.summary())
    issues = rotor.validate()
    for issue in issues:
        if issue.level == "ERROR":
            log.error("Rotor validation: %s", issue)
        elif issue.level == "WARNING":
            log.warning("Rotor validation: %s", issue)

    # Shadow module-level constants with rotor-definition values
    K_DRIVE_SPIN  = rotor.K_drive_Nms_m
    K_DRAG_SPIN   = rotor.K_drag_Nms2_rad2
    I_SPIN_KGMS2  = rotor.I_ode_kgm2
    OMEGA_SPIN_MIN = rotor.omega_min_rad_s

    _dyn_kw = rotor.dynamics_kwargs()
    # I_spin comes from rotor definition (beaupoil_2026: 0.0 — no gyroscopic coupling;
    # see comment above).  Do not add it separately.
    dynamics = RigidBodyDynamics(
        **_dyn_kw,
        pos0   = _dyn_pos0,
        vel0   = _dyn_vel0,
        R0     = _R0,
        omega0  = [0.0, 0.0, 0.0],    # orbital angular velocity only (no spin)
        z_floor = -1.0,               # safety net: NED Z ≤ -1 m (altitude ≥ 1 m)
    )
    sitl   = SITLInterface(
        recv_port=args.sitl_recv_port,
        send_port=args.sitl_send_port,
    )
    aero   = SkewedWakeBEM.from_definition(rotor)
    anchor_ned = np.array(cfg["anchor_ned"], dtype=float)
    tether = TetherModel(
        anchor_ned             = anchor_ned,
        rest_length            = float(cfg["tether_rest_length"]),
        hub_mass               = rotor.mass_kg,
        axle_attachment_length = 0.0,   # disable restoring torque; body_z stability via aero
    )
    sensor_sim = make_sensor(
        home_ned_z = float(_pos0_arr[2]),
    )
    spin_sensor = SpinSensor(
        sigma    = float(cfg["spin_sensor_sigma"]),
        K_drive  = K_DRIVE_SPIN,
        K_drag   = K_DRAG_SPIN,
    )
    log.info("Spin sensor: noise_sigma=%.3f rad/s", spin_sensor._sigma)
    log.info(
        "Tether: Dyneema SK75 1.9mm  EA=%.0f kN  rest_length=%.0f m  "
        "damping=%.1f N·s/m  break_load=%.0f N",
        tether.EA / 1000, tether.rest_length,
        tether.damping, tether.BREAK_LOAD_N,
    )

    # -- Connect ---------------------------------------------------------------
    log.info("Binding SITL UDP sockets...")
    sitl.bind()
    log.info("Python RigidBodyDynamics ready. Starting main loop.")

    # -- State ----------------------------------------------------------------
    t_sim           = 0.0
    step            = 0
    last_log_time   = -LOG_INTERVAL       # ensure immediate first log
    last_vel        = np.zeros(3)
    hub_state       = {
        "pos":   _dyn_pos0.copy(),
        "vel":   _dyn_vel0.copy(),
        "R":     _R0.copy(),
        "omega": np.array([0.0, 0.0, 0.0]),
    }
    last_servos        = np.zeros(16)   # neutral PWM (mapped from 1500µs → 0)
    s1 = s2 = s3       = 0.0           # servo values (updated in ArduPilot path; stale OK in IC path)
    _pc_free_t         = 0.0           # free-flight elapsed time [s]
    _traj_cmd          = {"phase": "", "tension_setpoint": 0.0}  # last trajectory command
    _logged_transition = False         # one-shot: kinematic → free-flight transition log
    omega_spin         = _omega_spin_init
    startup_damp_T     = _startup_damp_T   # already computed above
    startup_damp_k_ang = float(cfg["startup_damp_k_ang"])
    startup_vel_ramp_s = _vel_ramp_s       # vel ramp window at end of kinematic [s]
    t_ramp_start       = _t_ramp_start     # t_sim when ramp begins
    # Pre-compute ramp start position (constant throughout loop)
    _ramp_start_pos = _launch_pos + _vel0_arr * t_ramp_start if startup_damp_T > 0.0 else _pos0_arr.copy()
    log.info(
        "Startup damping: T=%.0fs  vel_ramp=%.0fs  k_ang=%.0f N*m*s/rad",
        startup_damp_T, startup_vel_ramp_s, startup_damp_k_ang,
    )

    # -- Telemetry CSV --------------------------------------------------------
    _telemetry_file   = None
    _telemetry_writer = None
    if args.telemetry_log:
        _telemetry_file = open(args.telemetry_log, "w", newline="", encoding="utf-8")  # noqa: WPS515
        _telemetry_writer = csv.writer(_telemetry_file)
        # CSV schema (see also: analysis/generate_flight_report.py for column usage)
        _telemetry_writer.writerow([
            # Time
            "t_sim",
            # Servo inputs (normalized, -1..+1)
            "servo_s1", "servo_s2", "servo_s3", "servo_esc",
            # Swashplate mixing outputs
            "collective_norm", "tilt_lon", "tilt_lat", "collective_rad",
            # Rotor spin estimate
            "omega_rotor",
            # Aerodynamic model internals
            "aero_T", "aero_v_axial", "aero_v_i", "aero_v_inplane", "aero_ramp",
            "aero_Q_drag", "aero_Q_drive",
            # Aerodynamic forces (NED world frame)
            "F_x", "F_y", "F_z", "M_x", "M_y", "M_z",
            # Hub state (NED world frame: X=North, Y=East, Z=Down)
            "hub_pos_x", "hub_pos_y", "hub_pos_z",
            "hub_vel_x", "hub_vel_y", "hub_vel_z",
            "hub_omega_x", "hub_omega_y", "hub_omega_z",
            # Hub acceleration (finite-difference)
            "hub_accel_x", "hub_accel_y", "hub_accel_z",
            # Tether state
            "tether_length", "tether_extension", "tether_tension",
            "tether_fx", "tether_fy", "tether_fz",
            "tether_slack",
            # Tether-relative attitude sent to ArduPilot [rad]
            "rpy_roll", "rpy_pitch", "rpy_yaw",
            # Pumping cycle (empty strings when --pumping-cycle not active)
            "pumping_phase", "tether_rest_length", "tension_setpoint",
            "collective_from_tension_ctrl",
        ])
        log.info("Telemetry logging → %s", args.telemetry_log)  # args.telemetry_log is a runtime CLI arg

    # -- WinchNode (separate MAVLink node, co-located physically with anchor) --
    # Encapsulates WinchController + Anemometer.  The planner communicates
    # with this node ONLY through get_telemetry() and receive_command().
    # The mediator calls update_sensors() to feed physics outputs in.
    _winch_node = WinchNode(
        winch=WinchController(
            rest_length      = float(cfg["tether_rest_length"]),
            tension_safety_n = float(cfg["tension_safety_n"]),
        ),
        anemometer=Anemometer(height_m=3.0),
    )
    _winch_node.update_sensors(0.0, wind_world)   # prime anemometer before planner init

    # -- Trajectory planner (ground station) ---------------------------------
    # Caller supplies a pre-built planner, or one is built from cfg["trajectory"].
    # Wind seed comes from the WinchNode anemometer -- NOT from wind_world directly.
    _pc_tension  = 0.0
    _pc_telemetry: dict = _winch_node.get_telemetry()
    if trajectory is not None:
        _trajectory = trajectory
    else:
        _trajectory = _mcfg.make_trajectory(
            cfg, wind_ned=_pc_telemetry["wind_ned"])
    log.info("Trajectory: %s", type(_trajectory).__name__)

    # -- Pixhawk collective denormalisation -----------------------------------
    # thrust [0..1] from SET_ATTITUDE_TARGET → collective_rad for aero model.
    # Mirrors Pixhawk set_throttle_out() passthrough (raws_mode.md §8.4).
    # Collective denormalisation range — read from trajectory config which is
    # always complete (config.load starts from DEFAULTS; no fallbacks here).
    _traj_cfg    = cfg["trajectory"]["deschutter"]
    _col_min_rad = float(_traj_cfg["col_min_rad"])
    _col_max_rad = float(_traj_cfg["col_max_rad"])

    # -- Mode_RAWES inner loops -----------------------------------------------
    # Runs at 400 Hz on the Pixhawk.  Receives COMMAND packets from the planner.
    # Orbit tracking: computes tether-aligned body_z_eq from current pos.
    # Collective: set_throttle_out(thrust) — direct passthrough (no PI on Pixhawk).
    # Winch: handled by WinchController above (ground station, not Pixhawk).
    _body_z_slew_rate     = float(cfg["body_z_slew_rate_rad_s"])
    _swashplate_phase_deg = float(cfg["swashplate_phase_deg"])
    _orbit_tracker: "OrbitTracker | None" = None   # created at free-flight start

    # -- Main loop ------------------------------------------------------------
    log.info("Entering main loop at %.0f Hz target.", 1.0 / DT_TARGET)

    try:
        t_wall_start = time.monotonic()

        while True:
            t_wall_loop = time.monotonic()
            t_sim = t_wall_loop - t_wall_start

            # ----------------------------------------------------------------
            # Step 1: Receive servo values from SITL (non-blocking)
            # ----------------------------------------------------------------
            new_servos = sitl.recv_servos()
            if new_servos is not None:
                last_servos = new_servos
            # Use last known servo values if no new packet
            servos = last_servos

            # ── Startup kinematic phase ───────────────────────────────────────
            # Hub moves at constant velocity (vel0) from launch_pos, arriving
            # at (pos0, vel0) at t=startup_damp_T.  Constant velocity means:
            #   - Non-zero velocity from frame 0 → EKF gets yaw heading immediately
            #   - Zero acceleration → IMU sees only gravity (clean EKF signal)
            # alpha=1 during kinematic phase, 0 in free flight.
            # ─────────────────────────────────────────────────────────────────
            if startup_damp_T > 0.0 and t_sim < startup_damp_T:
                _damp_alpha = 1.0 - (t_sim / startup_damp_T)
            else:
                _damp_alpha = 0.0

            # ----------------------------------------------------------------
            # Step 2: Swashplate commands
            #
            # Internal controller (--internal-controller, free flight only):
            #   Trajectory controller provides body_z_eq + collective at 400 Hz.
            #   Also updates tether.rest_length (winch) when active.
            #   ArduPilot servo outputs are ignored; SITL still runs for EKF.
            #
            # Normal path (ArduPilot servo PWM → H3-120 inverse mix):
            #   Servo channels 0,1,2 = S1,S2,S3 (swashplate); channel 3 = ESC
            #   Servos arrive normalised [-1,1] from SITLInterface
            # ----------------------------------------------------------------
            _pc_free_t = max(0.0, t_sim - startup_damp_T)
            esc_norm   = float(np.clip(servos[3], -1.0, 1.0))

            if cfg["internal_controller"] and _damp_alpha == 0.0:
                # ── STATE packet (Pixhawk → planner) ─────────────────────────
                # Mirrors standard ArduPilot telemetry streams:
                #   pos_ned / vel_ned  ← LOCAL_POSITION_NED
                #   omega_spin         ← ESC_STATUS[RAWES_CTR_ESC].rpm × gear formula
                # tension_n is local to the winch controller — not in this packet.
                # t_free is planner-owned — computed locally and passed separately.
                _state_pkt = {
                    "pos_ned":    hub_state["pos"],
                    "vel_ned":    hub_state["vel"],
                    "omega_spin": spin_sensor.measure(omega_spin),
                    "body_z":     hub_state["R"][:, 2],
                }
                _traj_cmd = _trajectory.step(
                    _state_pkt, DT_TARGET,
                    tension_n       = _pc_telemetry["tension_n"],
                    tether_length_m = _pc_telemetry["tether_length_m"],
                )
                # _traj_cmd: attitude_q, thrust [0..1], winch_speed_ms, phase

                # ── Mode_RAWES inner loops (400 Hz, runs on Pixhawk) ──────────

                # 1. Orbit tracking: create tracker on first free-flight step
                if _orbit_tracker is None:
                    _ic_tether_dir0 = hub_state["pos"] / np.linalg.norm(hub_state["pos"])
                    _orbit_tracker  = OrbitTracker(_bz, _ic_tether_dir0, _body_z_slew_rate)

                # 2. WinchNode (ground station) — apply speed command + safety limit
                _winch_node.receive_command(_traj_cmd["winch_speed_ms"], DT_TARGET)
                tether.rest_length = _winch_node.rest_length

                # 3. Collective from planner.
                #    DeschutterPlanner returns "collective_rad" directly — use it
                #    to avoid normalization/denormalization mismatch when col_min
                #    differs between reel-out (-0.28) and reel-in (-0.20) phases.
                #    HoldPlanner (and any legacy planner) only returns "thrust";
                #    fall back to thrust denormalization for those.
                if "collective_rad" in _traj_cmd:
                    collective_rad = float(_traj_cmd["collective_rad"])
                else:
                    collective_rad = _col_min_rad + _traj_cmd["thrust"] * (_col_max_rad - _col_min_rad)

                # 4. Attitude: orbit-track tether; rate-limited slerp toward
                #    attitude_q target when non-identity  (SET_ATTITUDE_TARGET)
                _aq = _traj_cmd["attitude_q"]
                _bz_target = (None if quat_is_identity(_aq)
                              else quat_apply(_aq, np.array([0.0, 0.0, -1.0])))
                _body_z_eq = _orbit_tracker.update(hub_state["pos"], DT_TARGET, _bz_target)

                swash = compute_swashplate_from_state(
                    hub_state=hub_state, anchor_pos=anchor_ned,
                    body_z_eq=_body_z_eq,
                    swashplate_phase_deg=_swashplate_phase_deg,
                    kp=0.30, kd=0.12)   # tuned for SkewedWakeBEM (5.4× more moment/tilt than RotorAero)
                tilt_lon        = swash["tilt_lon"]
                tilt_lat        = swash["tilt_lat"]
                collective_norm = 0.0   # for telemetry logging
            else:
                s1 = float(servos[0])
                s2 = float(servos[1])
                s3 = float(servos[2])
                collective_norm, tilt_lon, tilt_lat = h3_inverse_mix(s1, s2, s3)
                collective_rad = collective_to_pitch(collective_norm, _col_max_rad)

            # ----------------------------------------------------------------
            # Step 3: Compute aerodynamic forces
            # Use current hub state from previous dynamics step
            # ----------------------------------------------------------------
            R_hub = hub_state["R"]
            v_hub = hub_state["vel"]

            result = aero.compute_forces(
                collective_rad = collective_rad,
                tilt_lon       = tilt_lon,
                tilt_lat       = tilt_lat,
                R_hub          = R_hub,
                v_hub_world    = v_hub,
                omega_rotor    = omega_spin,   # separate spin state — never decays unexpectedly
                wind_world     = wind_world,
                t              = t_sim,
            )

            # ----------------------------------------------------------------
            # Step 4: Tether force (tension-only, Dyneema SK75 1.9 mm)
            # Skipped during kinematic startup: hub position is set by the
            # kinematic trajectory (which may be outside the tether envelope)
            # and translation is overridden after dynamics.step() anyway.
            # ----------------------------------------------------------------
            if _damp_alpha > 0.0:
                # Kinematic phase — hub position is controlled directly.
                # Skip tether (launch_pos is ~2 m further from anchor than
                # rest_length → would generate ~11 kN, well above break load).
                tether_force  = np.zeros(3)
                tether_moment = np.zeros(3)
            else:
                tether_force, tether_moment = tether.compute(
                    hub_state["pos"], hub_state["vel"], hub_state["R"])
                # Warn if tether tension approaches break load
                if tether._last_info.get("tension", 0) > 0.8 * tether.BREAK_LOAD_N:
                    log.warning(
                        "t=%.1f TETHER TENSION %.0f N is >80%% of break load (%.0f N)!",
                        t_sim, tether._last_info["tension"], tether.BREAK_LOAD_N,
                    )
                # Feed physics outputs into WinchNode; planner reads via get_telemetry().
                # wind_world is NOT accessible to the planner -- only the anemometer reading is.
                _winch_node.update_sensors(
                    tether._last_info.get("tension", 0.0), wind_world)
                _pc_telemetry = _winch_node.get_telemetry()
                _pc_tension   = _pc_telemetry["tension_n"]   # kept for break-load warning below

            # Build net force and moments (aero + tether) for dynamics and logging
            F_net     = result.F_world + tether_force
            M_orbital = result.M_orbital + tether_moment
            forces    = np.concatenate([F_net, M_orbital + result.M_spin])   # for telemetry log

            # ----------------------------------------------------------------
            # Step 4c: Thrust magnitude (for logging)
            # ----------------------------------------------------------------
            disk_normal = R_hub[:, 2]
            T_est = max(0.0, float(np.dot(F_net, disk_normal)))

            # ----------------------------------------------------------------
            # Step 4c: Update omega_spin from autorotation torque balance
            #
            # Q_drive ∝ v_inplane (wind energy extraction — does NOT depend on
            #   omega, so it has a different omega-scaling than Q_drag).
            # Q_drag  ∝ omega²   (profile drag — always opposes rotation).
            #
            # This gives a stable equilibrium omega_eq = sqrt(K_DRIVE × v_inplane / K_DRAG).
            # The BEM Q_drive/Q_drag terms are NOT used here because the BEM
            # torque also scales as omega² (through dynamic pressure), making
            # drive and drag parallel — no equilibrium exists and omega runs away.
            # Spin ODE — owned by the aero model via result.Q_spin
            omega_spin = max(OMEGA_SPIN_MIN,
                             omega_spin + result.Q_spin / I_SPIN_KGMS2 * DT_TARGET)

            # ----------------------------------------------------------------
            # Step 5: Integrate rigid-body dynamics (RK4, gravity internal)
            # F_net       = aero + tether force
            # M_orbital   = cyclic moments only (M_spin excluded — it updates omega_spin above)
            # omega_spin  passed for gyroscopic coupling in Euler equations
            # Do NOT add gravity here — dynamics.py applies it internally.
            # ----------------------------------------------------------------
            if cfg["lock_orientation"]:
                # Magic tether: no rotation allowed.  Pass zero moments so the
                # integrator never accelerates angular velocity, then forcibly
                # reset R and omega after the step to eliminate numerical drift.
                M_step = np.zeros(3)
            else:
                # Attitude rate damping: oppose orbital angular velocity to prevent
                # free tumbling.  The base term (--base-k-ang, default 50 N·m·s/rad)
                # prevents runaway tumbling at all times.  During the startup ramp
                # an additional term (startup_damp_k_ang) provides stronger damping
                # so the hub barely rotates while the EKF initialises.
                _k_ang_total = cfg["base_k_ang"] + startup_damp_k_ang * _damp_alpha
                M_orbital += -_k_ang_total * hub_state["omega"]
                M_step = M_orbital

            prev_vel  = hub_state["vel"].copy()
            hub_state = dynamics.step(F_net, M_step, DT_TARGET,
                                      omega_spin=omega_spin)
            new_vel   = hub_state["vel"]

            if cfg["lock_orientation"] and _damp_alpha == 0.0:
                # Track current tether direction: body_z = normalize(hub_pos).
                # This keeps the rotor disk aligned with the tether as the hub
                # orbits, while eliminating rotational tumbling (omega=0).
                # Locking to the INITIAL direction (_R0) was wrong: thrust would
                # stop being radial as the hub orbited, decelerating the orbit
                # via aero drag until the hub came to rest.
                # Only active during free flight — kinematic startup (below) takes
                # precedence and locks R to the equilibrium orientation _R0.
                _cur_body_z = hub_state["pos"] / np.linalg.norm(hub_state["pos"])
                hub_state["R"]     = build_orb_frame(_cur_body_z)
                hub_state["omega"] = np.zeros(3)

            # ----------------------------------------------------------------
            # Step 5b: Kinematic startup override — runs LAST so it always wins
            # over lock_orientation (which would set R to the launch-pos tether
            # direction, collapsing v_inplane and killing the spin equilibrium).
            #
            # During the startup window, override the full hub state with the
            # pre-computed kinematic trajectory.
            #
            # CRITICAL: orientation (R, omega) is locked to equilibrium _R0
            # as well as translation.  ACRO servo commands during startup
            # generate cyclic aerodynamic moments that would otherwise spin the
            # hub to a misaligned disk orientation before physics takes over,
            # causing thrust to collapse to zero at t=T.  By locking R=_R0 and
            # omega=0 throughout the kinematic window the hub arrives at t=T in
            # exactly the equilibrium orientation, ready for free flight.
            # ----------------------------------------------------------------
            if _damp_alpha > 0.0:
                # Compute kinematic position and velocity.
                # Before ramp: constant velocity.
                # During ramp (last startup_vel_ramp_s seconds): linear vel → 0.
                if startup_vel_ramp_s > 0.0 and t_sim >= t_ramp_start:
                    _u = t_sim - t_ramp_start          # time into ramp [0, ramp_s]
                    _ramp_frac = max(0.0, (startup_vel_ramp_s - _u) / startup_vel_ramp_s)
                    _kin_pos = (_ramp_start_pos
                                + _vel0_arr * _u * (1.0 - _u / (2.0 * startup_vel_ramp_s)))
                    _kin_vel = _vel0_arr * _ramp_frac
                else:
                    _kin_pos = _launch_pos + _vel0_arr * t_sim
                    _kin_vel = _vel0_arr.copy()
                hub_state["pos"]   = _kin_pos
                hub_state["vel"]   = _kin_vel
                hub_state["R"]     = _R0.copy()
                hub_state["omega"] = np.zeros(3)
                new_vel            = _kin_vel
                # Keep dynamics internal state in sync so the first free-flight
                # step integrates from the correct position, velocity, and orientation.
                dynamics._pos[:]   = _kin_pos
                dynamics._vel[:]   = _kin_vel
                dynamics._R[:]     = _R0
                dynamics._omega[:] = np.zeros(3)
            elif not _logged_transition:
                # ── First free-flight step — one-shot transition diagnostic ────
                # Logs the full hub state at the kinematic→free-flight boundary
                # so analysis scripts can compare against the unit-test initial
                # conditions (steady_state_starting.json, vel ≈ 0).
                _logged_transition = True
                _p  = hub_state["pos"]
                _v  = hub_state["vel"]
                _bz = hub_state["R"][:, 2]
                _om = hub_state["omega"]
                _ti = tether._last_info
                log.info(
                    "TRANSITION kinematic→free-flight at t=%.3f s", t_sim)
                log.info(
                    "  pos_NED  = [%.4f %.4f %.4f] m  altitude=%.3f m  "
                    "orbit_radius=%.3f m",
                    _p[0], _p[1], _p[2], -_p[2],
                    float(np.sqrt(_p[0]**2 + _p[1]**2)))
                log.info(
                    "  vel_NED  = [%.4f %.4f %.4f] m/s  |v|=%.4f m/s",
                    _v[0], _v[1], _v[2], float(np.linalg.norm(_v)))
                log.info(
                    "  body_z   = [%.4f %.4f %.4f]  omega=[%.4f %.4f %.4f] rad/s",
                    _bz[0], _bz[1], _bz[2], _om[0], _om[1], _om[2])
                log.info(
                    "  tether:  L=%.4f m  rest=%.4f m  ext=%.5f m  T=%.2f N  slack=%s",
                    _ti.get("length", 0.0), tether.rest_length,
                    _ti.get("extension", 0.0), _ti.get("tension", 0.0),
                    _ti.get("slack", True))
                log.info(
                    "  aero:    T_est=%.2f N  omega_spin=%.3f rad/s  col=%.4f rad",
                    T_est, omega_spin, collective_rad)

            # ----------------------------------------------------------------
            # Step 7: Compute hub acceleration (finite difference)
            # ----------------------------------------------------------------
            accel_world = (new_vel - prev_vel) / DT_TARGET

            # ----------------------------------------------------------------
            # Step 8: Build SITL sensor packet
            # ----------------------------------------------------------------
            sensor_data = sensor_sim.compute(
                pos_ned         = hub_state["pos"],
                vel_ned         = hub_state["vel"],
                R_hub           = hub_state["R"],
                omega_body      = hub_state["omega"],
                accel_world_ned = accel_world,
                dt              = DT_TARGET,
            )

            # ----------------------------------------------------------------
            # Step 8b: Write telemetry row (after sensor so rpy is available)
            # ----------------------------------------------------------------
            if _telemetry_writer is not None:
                _rpy = sensor_data["rpy"]
                _telemetry_writer.writerow([
                    f"{t_sim:.6f}",
                    f"{s1:.6f}", f"{s2:.6f}", f"{s3:.6f}", f"{esc_norm:.6f}",
                    f"{collective_norm:.6f}", f"{tilt_lon:.6f}", f"{tilt_lat:.6f}",
                    f"{collective_rad:.6f}",
                    f"{omega_spin:.4f}",
                    f"{aero.last_T:.4f}",
                    f"{aero.last_v_axial:.4f}",
                    f"{aero.last_v_i:.4f}",
                    f"{aero.last_v_inplane:.4f}",
                    f"{aero.last_ramp:.4f}",
                    f"{aero.last_Q_drag:.4f}",
                    f"{aero.last_Q_drive:.4f}",
                    f"{forces[0]:.4f}", f"{forces[1]:.4f}", f"{forces[2]:.4f}",
                    f"{forces[3]:.4f}", f"{forces[4]:.4f}", f"{forces[5]:.4f}",
                    f"{hub_state['pos'][0]:.4f}", f"{hub_state['pos'][1]:.4f}", f"{hub_state['pos'][2]:.4f}",
                    f"{hub_state['vel'][0]:.4f}", f"{hub_state['vel'][1]:.4f}", f"{hub_state['vel'][2]:.4f}",
                    f"{hub_state['omega'][0]:.4f}", f"{hub_state['omega'][1]:.4f}", f"{hub_state['omega'][2]:.4f}",
                    f"{accel_world[0]:.4f}", f"{accel_world[1]:.4f}", f"{accel_world[2]:.4f}",
                    f"{tether._last_info.get('length', 0.0):.4f}",
                    f"{tether._last_info.get('extension', 0.0):.4f}",
                    f"{tether._last_info.get('tension', 0.0):.4f}",
                    f"{tether_force[0]:.4f}", f"{tether_force[1]:.4f}", f"{tether_force[2]:.4f}",
                    "1" if tether._last_info.get("slack", True) else "0",
                    f"{_rpy[0]:.6f}", f"{_rpy[1]:.6f}", f"{_rpy[2]:.6f}",
                    # Trajectory columns (phase="hold" when pumping cycle inactive)
                    _traj_cmd.get("phase", ""),
                    f"{tether.rest_length:.4f}",
                    f"{_traj_cmd.get('tension_setpoint', 0.0):.2f}",
                    f"{collective_rad:.6f}",
                ])

            # ----------------------------------------------------------------
            # Step 9: Send physics state to SITL
            # ----------------------------------------------------------------
            sitl.send_state(
                timestamp  = t_sim,
                pos_ned    = sensor_data["pos_ned"],
                vel_ned    = sensor_data["vel_ned"],
                rpy_rad    = sensor_data["rpy"],
                accel_body = sensor_data["accel_body"],
                gyro_body  = sensor_data["gyro_body"],
                rpm_rad_s  = omega_spin,
            )

            # ----------------------------------------------------------------
            # Step 10: Periodic status log (1 Hz)
            # ----------------------------------------------------------------
            if t_sim - last_log_time >= LOG_INTERVAL:
                last_log_time = t_sim
                pos   = hub_state["pos"]
                vel   = hub_state["vel"]
                rpy_d = np.degrees(sensor_data["rpy"])
                teth  = tether._last_info
                teth_str = (
                    f"SLACK  L={teth.get('length',0):.1f}m"
                    if teth.get("slack", True) else
                    f"TAUT  T={teth.get('tension',0):.0f}N  ext={teth.get('extension',0):.3f}m"
                )
                damp_str = (
                    f"  [DAMP α={_damp_alpha:.2f} remaining={startup_damp_T - t_sim:.0f}s]"
                    if _damp_alpha > 0.0 else ""
                )
                log.info(
                    "t=%6.1fs  pos_NED=[%6.1f %6.1f %6.1f]m  alt=%.2fm  "
                    "rpy=[%5.1f %5.1f %5.1f]deg  "
                    "omega=%.1f rad/s  T=%.1fN  tether=%s%s",
                    t_sim,
                    pos[0], pos[1], pos[2], -pos[2],
                    rpy_d[0], rpy_d[1], rpy_d[2],
                    omega_spin,
                    T_est,
                    teth_str,
                    damp_str,
                )
                # Extra velocity detail for first 15 s of free flight
                # (helps diagnose kinematic→free-flight transition oscillations)
                t_free = t_sim - startup_damp_T
                if 0.0 <= t_free <= 15.0:
                    log.info(
                        "  vel_NED=[%.3f %.3f %.3f] m/s  |v|=%.3f  "
                        "orbit_r=%.2f m  col=%.4f rad  phase=%s",
                        vel[0], vel[1], vel[2], float(np.linalg.norm(vel)),
                        float(np.sqrt(pos[0]**2 + pos[1]**2)),
                        collective_rad,
                        _traj_cmd.get("phase", ""),
                    )

            # ----------------------------------------------------------------
            # Timing: sleep remainder of target period
            # ----------------------------------------------------------------
            elapsed = time.monotonic() - t_wall_loop
            remaining = DT_TARGET - elapsed
            if remaining > 0:
                time.sleep(remaining)

            step += 1

    except KeyboardInterrupt:
        log.info("KeyboardInterrupt received — shutting down.")

    except Exception as exc:
        log.exception("Fatal error in main loop: %s", exc)
        raise

    finally:
        # -- Graceful shutdown ------------------------------------------------
        log.info("Final state at step %d (t=%.2f s):", step, t_sim)
        log.info("  pos_NED : %s m",  hub_state["pos"].round(3))
        log.info("  vel_NED : %s m/s", hub_state["vel"].round(3))
        log.info("  omega_spin : %.2f rad/s", omega_spin)

        if _telemetry_file is not None:
            try:
                _telemetry_file.flush()
                _telemetry_file.close()
                log.info("Telemetry log closed.")
            except Exception:
                pass

        log.info("Closing connections ...")
        try:
            sitl.close()
        except Exception:
            pass
        log.info("Mediator stopped.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    args = _parse_args()
    logging.basicConfig(
        level    = getattr(logging, args.log_level.upper()),
        format   = "%(asctime)s %(levelname)-8s %(name)s: %(message)s",
        datefmt  = "%H:%M:%S",
    )
    run_mediator(args)


if __name__ == "__main__":
    main()
