#!/usr/bin/env python3
"""
RAWES Simulation Mediator
Bridges ArduPilot SITL <-> Python RK4 dynamics for end-to-end flight simulation.

Architecture:
    ArduPilot SITL  <--UDP 9002/9003-->  mediator.py  <--function call-->  dynamics.py (RK4)

Data flow (each 400 Hz step):
    1. recv_servos()     — non-blocking, from SITL UDP port 9002
    2. swashplate mix    — servo PWM -> collective + cyclic tilt
                          OR compute_swashplate_from_state() if --internal-controller
    3. aero.compute()    — BEM forces in world (ENU) frame
    4. tether.compute()  — tension-only tether force added to wrench
    5. dynamics.step()   — RK4 6-DOF integration (pure Python, gravity internal)
    6. sensor packet     — minimal NED state for ACRO mode (gyro + constant gravity)
    7. send_state()      — to SITL UDP port 9003

Usage:
    python3 mediator.py [options]

Options:
    --sitl-recv-port  PORT     SITL servo recv port  (default: 9002)
    --sitl-send-port  PORT     SITL state send port  (default: 9003)
    --wind-x  FLOAT            Initial wind E [m/s]  (default: 10.0)
    --wind-y  FLOAT            Initial wind N [m/s]  (default: 0.0)
    --wind-z  FLOAT            Initial wind U [m/s]  (default: 0.0)
    --log-level LEVEL          Logging level         (default: INFO)
"""

import argparse
import csv
import logging
import sys
import time
import os

import numpy as np

# Local modules (same directory)
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dynamics        import RigidBodyDynamics
from sitl_interface  import SITLInterface
from swashplate      import h3_inverse_mix, collective_to_pitch
from aero            import SkewedWakeBEMJit
from tether          import TetherModel
from frames          import build_orb_frame
from sensor          import make_sensor, SpinSensor
from controller      import compute_swashplate_from_state, OrbitTracker
from kinematic       import KinematicStartup, compute_launch_position  # noqa: F401
from winch           import WinchController
from winch_node      import WinchNode, Anemometer
from planner         import quat_apply, quat_is_identity
import config as _mcfg
import rotor_definition as _rd
from telemetry_csv import COLUMNS as _TEL_COLUMNS, TelRow as _TelRow
import sim_time as _stm

# ---------------------------------------------------------------------------
# Configuration defaults
# ---------------------------------------------------------------------------
DT_TARGET    = 1.0 / 400.0    # 400 Hz target loop rate [s]
LOG_INTERVAL = 1.0             # position/attitude log interval [s]
WEIGHT_N     = 294.3           # rotor weight [N] = 30 kg * 9.81 m/s²
I_SPIN_KGMS2 = 10.0            # rotor spin-axis moment of inertia [kg·m²]
OMEGA_SPIN_MIN = 0.5           # minimum spin rate clamp [rad/s]

# Spin torque model: Q_net = K_DRIVE * v_inplane − K_DRAG * omega²
#
# The BEM torque integral (Q_positive/Q_negative) cannot model the spin
# equilibrium correctly: because thrust scales as omega², the drive term also
# scales as omega², so drive always exceeds drag and omega runs away without
# limit.  Instead we use a physically-motivated two-term model:
#
#   Q_drive  = K_DRIVE_SPIN × v_inplane   (energy extracted from lateral wind,
#                                           constant for a given wind speed)
#   Q_drag   = K_DRAG_SPIN  × omega²      (profile + induced drag, ∝ rpm²)
#
# These have different omega-dependence, so they balance at a stable
# equilibrium omega_eq = sqrt(K_DRIVE × v_inplane / K_DRAG).
#
# Tuning (at design point: v_wind = 10 m/s → omega_eq = 28 rad/s, λ = 7):
#   K_DRIVE_SPIN × 10  =  K_DRAG_SPIN × 28²
#   Choose K_DRAG_SPIN so that at equilibrium the torque magnitude is ≈ 14 N·m
#   (plausible for a 5 kg, 2.5 m blade rotor):
#       K_DRAG_SPIN  = 14 / 28²  ≈ 0.01786 N·m·s²/rad²
#       K_DRIVE_SPIN = 0.01786 × 28² / 10 = 1.4 N·m·s/m
#
# At v = 20 m/s:  omega_eq = sqrt(1.4 × 20 / 0.01786) ≈ 39.6 rad/s  (higher wind → faster spin)
K_DRIVE_SPIN = 1.4      # N·m·s/m   (autorotation drive per unit in-plane wind speed)
K_DRAG_SPIN  = 0.01786  # N·m·s²/rad²  (profile drag coefficient)

# Default initial state — warmup-settled equilibrium from test_steady_flight.py.
# 50 m tether at ~30° elevation (ENU), body Z aligned with tether direction.
# Generated by running: pytest simulation/tests/unit/test_steady_flight.py
# Initial state defaults live in config.py (DEFAULTS dict) — single source of truth.


# compute_launch_position is imported from kinematic.py (see imports above).
# It is re-exported here so existing callers (test_startup_trajectory.py) continue
# to work with:  from mediator import compute_launch_position


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
def _parse_args():
    parser = argparse.ArgumentParser(
        description="RAWES Simulation Mediator — bridges ArduPilot SITL and Python RK4 dynamics",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--config", default=None,
                        help="Path to a JSON configuration file.  All physics and control "
                             "parameters live here.  See _CONFIG_DEFAULTS in mediator.py for "
                             "the full schema and default values.  Missing keys fall back to "
                             "defaults.")
    parser.add_argument("--run-id", type=int, default=None,
                        help="Integer run ID shared across all log files for this test run.")
    parser.add_argument("--sitl-recv-port", type=int, default=9002,
                        help="UDP port to listen on for SITL servo data")
    parser.add_argument("--sitl-send-port", type=int, default=9003,
                        help="UDP port to send physics state to SITL")
    parser.add_argument("--log-level", default="INFO",
                        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
                        help="Logging verbosity level")
    parser.add_argument("--telemetry-log", default=None,
                        help="Path for per-step CSV telemetry log")
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Main mediator loop
# ---------------------------------------------------------------------------
def run_mediator(args, trajectory=None):
    """
    Run the mediator loop.

    Parameters
    ----------
    args       : argparse.Namespace — CLI arguments (ports, log level, etc.)
    trajectory : TrajectoryController or None
        Pre-constructed trajectory controller.  When provided, the mediator
        uses it directly.  When None (default), a controller is built from
        the ``cfg["trajectory"]`` section of the config file — this is the
        standard path when running as a subprocess launched by stack tests.
        Callers that want full control pass a pre-built object; the config
        section is only needed for subprocess/CLI use.
    """
    import time as _time_mod
    log = logging.getLogger("mediator")

    cfg = _mcfg.load(getattr(args, "config", None))

    # Emit a run-ID so post-run analysis can verify all log files belong to
    # the same test run.  Format: RUN_ID=<integer epoch seconds>.
    # Authoritative source: conftest.py generates once and passes via --run-id.
    # When run standalone (no --run-id), generate locally as fallback.
    _run_id = args.run_id if args.run_id is not None else int(_time_mod.time())
    log.info("RUN_ID=%d", _run_id)

    wind_world = np.array(cfg["wind"])
    log.info("Wind vector (NED): %s m/s", wind_world)

    # -- Instantiate subsystems -----------------------------------------------
    # Mass 30 kg: the blade geometry (4 × 2 m, chord 0.15 m) was scaled from
    # the De Schutter (2018) 40 kg reference design.  At the design tip-speed
    # ratio (λ = 7, v_wind = 10 m/s → ω = 28 rad/s) the BEM model produces
    # ~300 N of thrust at neutral collective — consistent with a ~30 kg rotor
    # hovering near its natural autorotation equilibrium.  Using 5 kg (actual
    # hardware mass) causes 6× over-thrust and makes the altitude controller
    # saturate.  TODO: either retune the blade geometry to the actual mass, or
    # verify the hardware mass is correct (5 kg seems very light for this blade
    # area and tip speed).
    # I_spin=0: do NOT include rotor gyroscopic coupling in the orbital dynamics.
    # The lumped single-body model uses ArduPilot's cyclic commands directly as
    # tilting moments (no blade flapping model).  The 90° gyroscopic precession
    # that a real spinning rotor would produce is already compensated by the
    # swashplate phase angle in a real helicopter; adding it here without the
    # corresponding phase compensation would cause ArduPilot's attitude
    # controller to tilt the disk in the wrong direction.
    # ── Initial state ──────────────────────────────────────────────────────────
    _pos0_arr        = np.array(cfg["pos0"],     dtype=float)
    _vel0_arr        = np.array(cfg["vel0"],     dtype=float)
    _omega_spin_init = float(cfg["omega_spin"])
    _bz_raw          = np.array(cfg["body_z"],   dtype=float)
    _bz = _bz_raw / np.linalg.norm(_bz_raw)

    # Build _R0: body-X is the East-projection of _bz.
    _R0 = build_orb_frame(_bz)

    # -- Kinematic startup trajectory -----------------------------------------
    _startup = KinematicStartup(
        target_pos = _pos0_arr,
        target_vel = _vel0_arr,
        duration   = max(0.0, float(cfg["startup_damp_seconds"])),
        ramp_s     = float(cfg["kinematic_vel_ramp_s"]),
        R0         = _R0,
    )
    if _startup.duration > 0.0:
        log.info(
            "Kinematic startup: T=%.0fs  ramp=%.0fs  "
            "launch_pos=[%.3f, %.3f, %.3f]  vel=[%.5f, %.5f, %.5f] m/s",
            _startup.duration, _startup.ramp_s,
            *_startup.launch_pos, *_vel0_arr,
        )
    _dyn_pos0 = _startup.launch_pos
    _dyn_vel0 = _vel0_arr

    rotor  = _rd.load(cfg["rotor_definition"])
    log.info("Rotor: %s", rotor.summary())
    issues = rotor.validate()
    for issue in issues:
        if issue.level == "ERROR":
            log.error("Rotor validation: %s", issue)
        elif issue.level == "WARNING":
            log.warning("Rotor validation: %s", issue)

    # Shadow module-level constants with rotor-definition values
    K_DRIVE_SPIN  = rotor.K_drive_Nms_m
    K_DRAG_SPIN   = rotor.K_drag_Nms2_rad2
    I_SPIN_KGMS2  = rotor.I_ode_kgm2
    OMEGA_SPIN_MIN = rotor.omega_min_rad_s

    _dyn_kw = rotor.dynamics_kwargs()
    # I_spin comes from rotor definition (beaupoil_2026: 0.0 — no gyroscopic coupling;
    # see comment above).  Do not add it separately.
    dynamics = RigidBodyDynamics(
        **_dyn_kw,
        pos0   = _dyn_pos0,
        vel0   = _dyn_vel0,
        R0     = _R0,
        omega0  = [0.0, 0.0, 0.0],    # orbital angular velocity only (no spin)
        z_floor = -1.0,               # safety net: NED Z ≤ -1 m (altitude ≥ 1 m)
    )
    sitl   = SITLInterface(
        recv_port=args.sitl_recv_port,
        send_port=args.sitl_send_port,
    )
    aero   = SkewedWakeBEMJit.from_definition(rotor)
    anchor_ned = np.array(cfg["anchor_ned"], dtype=float)
    tether = TetherModel(
        anchor_ned             = anchor_ned,
        rest_length            = float(cfg["tether_rest_length"]),
        hub_mass               = rotor.mass_kg,
        axle_attachment_length = rotor.axle_attachment_length_m,
    )
    sensor_sim = make_sensor(
        home_ned_z  = float(_pos0_arr[2]),
        initial_vel = _vel0_arr,
        initial_R   = _R0,
    )
    spin_sensor = SpinSensor(
        sigma    = float(cfg["spin_sensor_sigma"]),
        K_drive  = K_DRIVE_SPIN,
        K_drag   = K_DRAG_SPIN,
    )
    log.info("Spin sensor: noise_sigma=%.3f rad/s", spin_sensor._sigma)
    log.info(
        "Tether: Dyneema SK75 1.9mm  EA=%.0f kN  rest_length=%.0f m  "
        "damping=%.1f N·s/m  break_load=%.0f N",
        tether.EA / 1000, tether.rest_length,
        tether.damping, tether.BREAK_LOAD_N,
    )

    # -- Connect ---------------------------------------------------------------
    log.info("Binding SITL UDP sockets...")
    sitl.bind()
    log.info("Python RigidBodyDynamics ready. Starting main loop.")

    # -- State ----------------------------------------------------------------
    t_wall_start    = time.monotonic()   # wall-clock reference for sim time
    t_sim           = 0.0
    step            = 0
    last_log_time   = -LOG_INTERVAL       # ensure immediate first log
    hub_state       = {
        "pos":   _dyn_pos0.copy(),
        "vel":   _dyn_vel0.copy(),
        "R":     _R0.copy(),
        "omega": np.array([0.0, 0.0, 0.0]),
    }
    last_servos        = np.zeros(16)   # neutral PWM (mapped from 1500µs → 0)
    s1 = s2 = s3       = 0.0           # servo values (updated in ArduPilot path; stale OK in IC path)
    _body_z_eq         = np.zeros(3)   # body_z setpoint (IC path only; zeros in ArduPilot path)
    _traj_cmd          = {"phase": "", "tension_setpoint": 0.0}  # last trajectory command
    _logged_transition = False         # one-shot: kinematic → free-flight transition log
    _tel_note          = ""            # single-frame event marker written to telemetry CSV; cleared after write
    _prev_phase        = ""            # detect phase changes for tel note
    omega_spin         = _omega_spin_init
    startup_damp_k_ang = float(cfg["startup_damp_k_ang"])
    log.info(
        "Startup damping: T=%.0fs  vel_ramp=%.0fs  k_ang=%.0f N*m*s/rad",
        _startup.duration, _startup.ramp_s, startup_damp_k_ang,
    )

    # -- Telemetry CSV --------------------------------------------------------
    _telemetry_file   = None
    _telemetry_writer = None
    if args.telemetry_log:
        _telemetry_file = open(args.telemetry_log, "w", newline="", encoding="utf-8")  # noqa: WPS515
        _telemetry_writer = csv.DictWriter(_telemetry_file, fieldnames=_TEL_COLUMNS)
        _telemetry_writer.writeheader()
        log.info("Telemetry logging -> %s", args.telemetry_log)  # args.telemetry_log is a runtime CLI arg

    # -- WinchNode (separate MAVLink node, co-located physically with anchor) --
    # Encapsulates WinchController + Anemometer.  The planner communicates
    # with this node ONLY through get_telemetry() and receive_command().
    # The mediator calls update_sensors() to feed physics outputs in.
    _winch_node = WinchNode(
        winch=WinchController(
            rest_length      = float(cfg["tether_rest_length"]),
            tension_safety_n = float(cfg["tension_safety_n"]),
        ),
        anemometer=Anemometer(height_m=3.0),
    )
    _winch_node.update_sensors(0.0, wind_world)   # prime anemometer before planner init

    # -- Trajectory planner (ground station) ---------------------------------
    # Caller supplies a pre-built planner, or one is built from cfg["trajectory"].
    # Wind seed comes from the WinchNode anemometer -- NOT from wind_world directly.
    _pc_telemetry: dict = _winch_node.get_telemetry()
    if trajectory is not None:
        _trajectory = trajectory
    else:
        _trajectory = _mcfg.make_trajectory(
            cfg, wind_ned=_pc_telemetry["wind_ned"])
    log.info("Trajectory: %s", type(_trajectory).__name__)

    # -- Pixhawk collective denormalisation -----------------------------------
    # thrust [0..1] from SET_ATTITUDE_TARGET → collective_rad for aero model.
    # Mirrors Pixhawk set_throttle_out() passthrough (raws_mode.md §8.4).
    # Collective denormalisation range — read from trajectory config which is
    # always complete (config.load starts from DEFAULTS; no fallbacks here).
    _traj_cfg    = cfg["trajectory"]["deschutter"]
    _col_min_rad = float(_traj_cfg["col_min_rad"])
    _col_max_rad = float(_traj_cfg["col_max_rad"])

    # -- Mode_RAWES inner loops -----------------------------------------------
    # Runs at 400 Hz on the Pixhawk.  Receives COMMAND packets from the planner.
    # Orbit tracking: computes tether-aligned body_z_eq from current pos.
    # Collective: set_throttle_out(thrust) — direct passthrough (no PI on Pixhawk).
    # Winch: handled by WinchController above (ground station, not Pixhawk).
    _body_z_slew_rate     = float(cfg["body_z_slew_rate_rad_s"])
    _swashplate_phase_deg = float(cfg["swashplate_phase_deg"])
    _orbit_tracker: "OrbitTracker | None" = None   # created at free-flight start

    # -- Fast mode ------------------------------------------------------------
    log.info("Entering main loop at %.0f Hz target.", 1.0 / DT_TARGET)

    # -- Main loop ------------------------------------------------------------
    # t_sim is an accumulator (not wall-time derived) so it stays correct at
    # any speedup.  At 1x with the rate-limiter sleep the step period is
    # ~DT_TARGET wall-seconds, so the accumulator tracks wall-time closely.
    # In fast mode the sleep is skipped; the loop runs at max Python speed.

    try:
        while True:
            t_wall_loop = time.monotonic()

            # ----------------------------------------------------------------
            # Step 1: Receive servo values from SITL
            #   Normal mode : non-blocking (returns None on timeout → reuse last)
            #   Fast mode   : blocking until SITL replies (1:1 lockstep)
            # ----------------------------------------------------------------
            new_servos = sitl.recv_servos()
            if new_servos is not None:
                last_servos = new_servos
            servos = last_servos

            # ── Startup kinematic phase ───────────────────────────────────────
            # Hub moves at constant velocity (vel0) from launch_pos, arriving
            # at (pos0, vel0) at t=duration.  Constant velocity means:
            #   - Non-zero velocity from frame 0 → EKF gets yaw heading immediately
            #   - Zero acceleration → IMU sees only gravity (clean EKF signal)
            # alpha=1 during kinematic phase, 0 in free flight.
            # ─────────────────────────────────────────────────────────────────
            _damp_alpha = _startup.damp_alpha(t_sim)

            # ----------------------------------------------------------------
            # Step 2: Swashplate commands
            #
            # Internal controller (--internal-controller, free flight only):
            #   Trajectory controller provides body_z_eq + collective at 400 Hz.
            #   Also updates tether.rest_length (winch) when active.
            #   ArduPilot servo outputs are ignored; SITL still runs for EKF.
            #
            # Normal path (ArduPilot servo PWM → H3-120 inverse mix):
            #   Servo channels 0,1,2 = S1,S2,S3 (swashplate); channel 3 = ESC
            #   Servos arrive normalised [-1,1] from SITLInterface
            # ----------------------------------------------------------------
            esc_norm   = float(np.clip(servos[3], -1.0, 1.0))

            # ----------------------------------------------------------------
            # Step 2a: Tether force (pre-computed before the planner call)
            #
            # The trajectory planner (TensionPI) needs the CURRENT tether
            # tension on every step, including the very first free-flight step
            # right after kinematic exit.  Computing the tether here — using
            # hub_state from the previous dynamics step, exactly like the
            # planner itself — ensures tension_n is never stale.
            #
            # Without this, the first free-flight call to _trajectory.step()
            # sees tension_n=0 (left over from the kinematic phase), so
            # TensionPI warm-starts at collective≈-0.08 rad instead of the
            # ~-0.20 rad equilibrium.  This causes a large thrust overshoot
            # that drives the hub to the ground in the first 20 s of reel-out.
            #
            # Skipped during kinematic startup: hub position is set by the
            # kinematic trajectory (which may be outside the tether envelope)
            # and translation is overridden after dynamics.step() anyway.
            # ----------------------------------------------------------------
            if _damp_alpha > 0.0:
                tether_force  = np.zeros(3)
                tether_moment = np.zeros(3)
            else:
                tether_force, tether_moment = tether.compute(
                    hub_state["pos"], hub_state["vel"], hub_state["R"])
                if tether._last_info.get("tension", 0) > 0.8 * tether.BREAK_LOAD_N:
                    log.warning(
                        "t=%.1f TETHER TENSION %.0f N is >80%% of break load (%.0f N)!",
                        t_sim, tether._last_info["tension"], tether.BREAK_LOAD_N,
                    )
                # Feed physics outputs into WinchNode; planner reads via get_telemetry().
                # wind_world is NOT accessible to the planner -- only the anemometer reading is.
                _winch_node.update_sensors(
                    tether._last_info.get("tension", 0.0), wind_world)
                _pc_telemetry = _winch_node.get_telemetry()

            if _damp_alpha == 0.0:
                # ── Ground-station trajectory planner (always runs in free flight) ──
                # Runs regardless of internal_controller flag so that ground-station
                # actuators (winch) are always controlled by the planner.
                # When internal_controller=True the planner also drives collective and
                # attitude; when False those come from ArduPilot/Lua RC overrides.
                _state_pkt = {
                    "pos_ned":    hub_state["pos"],
                    "vel_ned":    hub_state["vel"],
                    "omega_spin": spin_sensor.measure(omega_spin),
                    "body_z":     hub_state["R"][:, 2],
                }
                _traj_cmd = _trajectory.step(
                    _state_pkt, DT_TARGET,
                    tension_n       = _pc_telemetry["tension_n"],
                    tether_length_m = _pc_telemetry["tether_length_m"],
                )

                # WinchNode (ground station) — apply speed command + safety limit
                _winch_node.receive_command(_traj_cmd["winch_speed_ms"], DT_TARGET)
                tether.rest_length = _winch_node.rest_length

            if cfg["internal_controller"] and _damp_alpha == 0.0:
                # ── Mode_RAWES inner loops (400 Hz, runs on Pixhawk) ──────────
                # Internal controller: planner also drives collective and attitude.
                # Used when ArduPilot RC overrides are too slow (pumping cycle).

                # 1. Orbit tracking: create tracker on first free-flight step
                if _orbit_tracker is None:
                    _bz = hub_state["R"][:, 2]
                    _ic_tether_dir0 = hub_state["pos"] / np.linalg.norm(hub_state["pos"])
                    _orbit_tracker  = OrbitTracker(_bz, _ic_tether_dir0, _body_z_slew_rate)

                # 2. Collective from planner.
                #    DeschutterPlanner returns "collective_rad" directly — use it
                #    to avoid normalization/denormalization mismatch when col_min
                #    differs between reel-out (-0.28) and reel-in (-0.20) phases.
                #    HoldPlanner (and any legacy planner) only returns "thrust";
                #    fall back to thrust denormalization for those.
                if "collective_rad" in _traj_cmd:
                    collective_rad = float(_traj_cmd["collective_rad"])
                else:
                    collective_rad = _col_min_rad + _traj_cmd["thrust"] * (_col_max_rad - _col_min_rad)

                # 3. Attitude: orbit-track tether; rate-limited slerp toward
                #    attitude_q target when non-identity  (SET_ATTITUDE_TARGET)
                _aq = _traj_cmd["attitude_q"]
                _bz_target = (None if quat_is_identity(_aq)
                              else quat_apply(_aq, np.array([0.0, 0.0, -1.0])))
                _body_z_eq = _orbit_tracker.update(hub_state["pos"], DT_TARGET, _bz_target)

                swash = compute_swashplate_from_state(
                    hub_state=hub_state, anchor_pos=anchor_ned,
                    body_z_eq=_body_z_eq,
                    swashplate_phase_deg=_swashplate_phase_deg,
                    kp=float(cfg["cyclic_kp"]),
                    kd=float(cfg["cyclic_kd"]))
                tilt_lon        = swash["tilt_lon"]
                tilt_lat        = swash["tilt_lat"]
                collective_norm = 0.0   # for telemetry logging
            else:
                s1 = float(servos[0])
                s2 = float(servos[1])
                s3 = float(servos[2])
                collective_norm, tilt_lon, tilt_lat = h3_inverse_mix(s1, s2, s3)
                # Asymmetric decode: Lua encodes col_rad in [col_min, col_max] as
                # thrust = (col_rad - col_min) / (col_max - col_min), ch3 = 1000 + thrust*1000.
                # With H_COL_MIN=1000/H_COL_MAX=2000: servo_norm = thrust*2 - 1.
                # Inverse: thrust = (collective_norm + 1) / 2.
                _col_thrust = (collective_norm + 1.0) / 2.0
                collective_rad = float(np.clip(
                    _col_min_rad + _col_thrust * (_col_max_rad - _col_min_rad),
                    _col_min_rad, _col_max_rad,
                ))

            # ----------------------------------------------------------------
            # Step 3: Compute aerodynamic forces
            # Use current hub state from previous dynamics step
            # ----------------------------------------------------------------
            R_hub = hub_state["R"]
            v_hub = hub_state["vel"]

            result = aero.compute_forces(
                collective_rad = collective_rad,
                tilt_lon       = tilt_lon,
                tilt_lat       = tilt_lat,
                R_hub          = R_hub,
                v_hub_world    = v_hub,
                omega_rotor    = omega_spin,   # separate spin state — never decays unexpectedly
                wind_world     = wind_world,
                t              = t_sim,
            )

            # ----------------------------------------------------------------
            # Step 4: Tether force — already computed in Step 2a above.
            # tether_force / tether_moment are set; WinchNode sensors updated.
            # ----------------------------------------------------------------

            # Build net force and moments (aero + tether) for dynamics and logging
            F_net     = result.F_world + tether_force
            M_orbital = result.M_orbital + tether_moment
            forces    = np.concatenate([F_net, M_orbital + result.M_spin])   # for telemetry log

            # ----------------------------------------------------------------
            # Step 4c: Thrust magnitude (for logging)
            # ----------------------------------------------------------------
            disk_normal = R_hub[:, 2]
            T_est = max(0.0, float(np.dot(F_net, disk_normal)))

            # ----------------------------------------------------------------
            # Step 4c: Update omega_spin from autorotation torque balance
            #
            # Q_drive ∝ v_inplane (wind energy extraction — does NOT depend on
            #   omega, so it has a different omega-scaling than Q_drag).
            # Q_drag  ∝ omega²   (profile drag — always opposes rotation).
            #
            # This gives a stable equilibrium omega_eq = sqrt(K_DRIVE × v_inplane / K_DRAG).
            # The BEM Q_drive/Q_drag terms are NOT used here because the BEM
            # torque also scales as omega² (through dynamic pressure), making
            # drive and drag parallel — no equilibrium exists and omega runs away.
            # Spin ODE — owned by the aero model via result.Q_spin
            omega_spin = max(OMEGA_SPIN_MIN,
                             omega_spin + result.Q_spin / I_SPIN_KGMS2 * DT_TARGET)

            # ----------------------------------------------------------------
            # Step 5: Integrate rigid-body dynamics (RK4, gravity internal)
            # F_net       = aero + tether force
            # M_orbital   = cyclic moments only (M_spin excluded — it updates omega_spin above)
            # omega_spin  passed for gyroscopic coupling in Euler equations
            # Do NOT add gravity here — dynamics.py applies it internally.
            # ----------------------------------------------------------------
            if cfg["lock_orientation"]:
                # Magic tether: no rotation allowed.  Pass zero moments so the
                # integrator never accelerates angular velocity, then forcibly
                # reset R and omega after the step to eliminate numerical drift.
                M_step = np.zeros(3)
            else:
                # Attitude rate damping: oppose orbital angular velocity to prevent
                # free tumbling.  The base term (--base-k-ang, default 50 N·m·s/rad)
                # prevents runaway tumbling at all times.  During the startup ramp
                # an additional term (startup_damp_k_ang) provides stronger damping
                # so the hub barely rotates while the EKF initialises.
                _k_ang_total = cfg["base_k_ang"] + startup_damp_k_ang * _damp_alpha
                M_orbital += -_k_ang_total * hub_state["omega"]
                M_step = M_orbital

            prev_vel  = hub_state["vel"].copy()
            hub_state = dynamics.step(F_net, M_step, DT_TARGET,
                                      omega_spin=omega_spin)
            new_vel   = hub_state["vel"]

            if cfg["lock_orientation"] and _damp_alpha == 0.0:
                # Track current tether direction: body_z = normalize(hub_pos).
                # This keeps the rotor disk aligned with the tether as the hub
                # orbits, while eliminating rotational tumbling (omega=0).
                # Locking to the INITIAL direction (_R0) was wrong: thrust would
                # stop being radial as the hub orbited, decelerating the orbit
                # via aero drag until the hub came to rest.
                # Only active during free flight — kinematic startup (below) takes
                # precedence and locks R to the equilibrium orientation _R0.
                _cur_body_z = hub_state["pos"] / np.linalg.norm(hub_state["pos"])
                hub_state["R"]     = build_orb_frame(_cur_body_z)
                hub_state["omega"] = np.zeros(3)

            # ----------------------------------------------------------------
            # Step 5b: Kinematic startup override — runs LAST so it always wins
            # over lock_orientation (which would set R to the launch-pos tether
            # direction, collapsing v_inplane and killing the spin equilibrium).
            #
            # During the startup window, override the full hub state with the
            # pre-computed kinematic trajectory.
            #
            # CRITICAL: orientation (R, omega) is locked to equilibrium _R0
            # as well as translation.  ACRO servo commands during startup
            # generate cyclic aerodynamic moments that would otherwise spin the
            # hub to a misaligned disk orientation before physics takes over,
            # causing thrust to collapse to zero at t=T.  By locking R=_R0 and
            # omega=0 throughout the kinematic window the hub arrives at t=T in
            # exactly the equilibrium orientation, ready for free flight.
            # ----------------------------------------------------------------
            if _startup.apply(hub_state, dynamics, t_sim):
                new_vel = hub_state["vel"]
            elif not _logged_transition:
                # ── First free-flight step — one-shot transition diagnostic ────
                # Logs the full hub state at the kinematic→free-flight boundary
                # so analysis scripts can compare against the unit-test initial
                # conditions (steady_state_starting.json, vel ≈ 0).
                _logged_transition = True
                _tel_note = "kinematic_exit"
                _p  = hub_state["pos"]
                _v  = hub_state["vel"]
                _bz = hub_state["R"][:, 2]
                _om = hub_state["omega"]
                _ti = tether._last_info
                log.info(
                    "TRANSITION kinematic→free-flight at t=%.3f s", t_sim)
                log.info(
                    "  pos_NED  = [%.4f %.4f %.4f] m  altitude=%.3f m  "
                    "orbit_radius=%.3f m",
                    _p[0], _p[1], _p[2], -_p[2],
                    float(np.sqrt(_p[0]**2 + _p[1]**2)))
                log.info(
                    "  vel_NED  = [%.4f %.4f %.4f] m/s  |v|=%.4f m/s",
                    _v[0], _v[1], _v[2], float(np.linalg.norm(_v)))
                log.info(
                    "  body_z   = [%.4f %.4f %.4f]  omega=[%.4f %.4f %.4f] rad/s",
                    _bz[0], _bz[1], _bz[2], _om[0], _om[1], _om[2])
                log.info(
                    "  tether:  L=%.4f m  rest=%.4f m  ext=%.5f m  T=%.2f N  slack=%s",
                    _ti.get("length", 0.0), tether.rest_length,
                    _ti.get("extension", 0.0), _ti.get("tension", 0.0),
                    _ti.get("slack", True))
                log.info(
                    "  aero:    T_est=%.2f N  omega_spin=%.3f rad/s  col=%.4f rad",
                    T_est, omega_spin, collective_rad)

            # ----------------------------------------------------------------
            # Step 7: Compute hub acceleration (finite difference)
            # ----------------------------------------------------------------
            accel_world = (new_vel - prev_vel) / DT_TARGET

            # ----------------------------------------------------------------
            # Step 8: Build SITL sensor packet
            # ----------------------------------------------------------------
            sensor_data = sensor_sim.compute(
                pos_ned         = hub_state["pos"],
                vel_ned         = hub_state["vel"],
                R_hub           = hub_state["R"],
                omega_body      = hub_state["omega"],
                accel_world_ned = accel_world,
                dt              = DT_TARGET,
            )

            # ----------------------------------------------------------------
            # Step 8b: Write telemetry row (after sensor so rpy is available)
            # ----------------------------------------------------------------
            if _telemetry_writer is not None:
                _rpy = sensor_data["rpy"]
                _ti  = tether._last_info
                _cur_phase = _traj_cmd.get("phase", "")
                if _cur_phase and _cur_phase != _prev_phase and not _tel_note:
                    _tel_note = f"phase_{_cur_phase.replace('-', '_')}_start"
                _prev_phase = _cur_phase
                _telemetry_writer.writerow({
                    "t_sim":           t_sim,
                    "phase":           _cur_phase,
                    "note":            _tel_note,
                    "damp_alpha":      _damp_alpha,
                    "pos_x":           hub_state["pos"][0],
                    "pos_y":           hub_state["pos"][1],
                    "pos_z":           hub_state["pos"][2],
                    "vel_x":           hub_state["vel"][0],
                    "vel_y":           hub_state["vel"][1],
                    "vel_z":           hub_state["vel"][2],
                    "omega_x":         hub_state["omega"][0],
                    "omega_y":         hub_state["omega"][1],
                    "omega_z":         hub_state["omega"][2],
                    "accel_x":         accel_world[0],
                    "accel_y":         accel_world[1],
                    "accel_z":         accel_world[2],
                    "omega_rotor":     omega_spin,
                    "tether_length":   _ti.get("length",    0.0),
                    "tether_extension":_ti.get("extension", 0.0),
                    "tether_tension":  _ti.get("tension",   0.0),
                    "tether_rest_length": tether.rest_length,
                    "tether_slack":    1 if _ti.get("slack", True) else 0,
                    "tether_fx":       tether_force[0],
                    "tether_fy":       tether_force[1],
                    "tether_fz":       tether_force[2],
                    "collective_rad":  collective_rad,
                    "collective_norm": collective_norm,
                    "tilt_lon":        tilt_lon,
                    "tilt_lat":        tilt_lat,
                    "tension_setpoint":           _traj_cmd.get("tension_setpoint", 0.0),
                    "collective_from_tension_ctrl": collective_rad,
                    "aero_T":          aero.last_T,
                    "aero_v_axial":    aero.last_v_axial,
                    "aero_v_inplane":  aero.last_v_inplane,
                    "aero_v_i":        aero.last_v_i,
                    "aero_Q_drag":     aero.last_Q_drag,
                    "aero_Q_drive":    aero.last_Q_drive,
                    "F_x":             forces[0],
                    "F_y":             forces[1],
                    "F_z":             forces[2],
                    "M_x":             forces[3],
                    "M_y":             forces[4],
                    "M_z":             forces[5],
                    "rpy_roll":        _rpy[0],
                    "rpy_pitch":       _rpy[1],
                    "rpy_yaw":         _rpy[2],
                    "orb_yaw_rad":     sensor_data.get("orb_yaw_rad", 0.0),
                    "v_horiz_ms":      sensor_data.get("v_horiz_ms",  0.0),
                    "servo_s1":        s1,
                    "servo_s2":        s2,
                    "servo_s3":        s3,
                    "servo_esc":       esc_norm,
                    "wind_x":          wind_world[0],
                    "wind_y":          wind_world[1],
                    "wind_z":          wind_world[2],
                    "bz_eq_x":         _body_z_eq[0],
                    "bz_eq_y":         _body_z_eq[1],
                    "bz_eq_z":         _body_z_eq[2],
                    "r00": float(hub_state["R"][0, 0]),
                    "r01": float(hub_state["R"][0, 1]),
                    "r02": float(hub_state["R"][0, 2]),
                    "r10": float(hub_state["R"][1, 0]),
                    "r11": float(hub_state["R"][1, 1]),
                    "r12": float(hub_state["R"][1, 2]),
                    "r20": float(hub_state["R"][2, 0]),
                    "r21": float(hub_state["R"][2, 1]),
                    "r22": float(hub_state["R"][2, 2]),
                })
                _tel_note = ""  # stamp only on the single event frame

            # ----------------------------------------------------------------
            # Step 9: Send physics state to SITL
            # ----------------------------------------------------------------
            sitl.send_state(
                timestamp  = t_sim,
                pos_ned    = sensor_data["pos_ned"],
                vel_ned    = sensor_data["vel_ned"],
                rpy_rad    = sensor_data["rpy"],
                accel_body = sensor_data["accel_body"],
                gyro_body  = sensor_data["gyro_body"],
                rpm_rad_s  = omega_spin,
            )

            # ----------------------------------------------------------------
            # Step 10: Periodic status log (1 Hz)
            # ----------------------------------------------------------------
            if t_sim - last_log_time >= LOG_INTERVAL:
                last_log_time = t_sim
                vel  = hub_state["vel"]
                _ti  = tether._last_info
                _hb  = _TelRow(
                    t_sim            = t_sim,
                    pos_x            = hub_state["pos"][0],
                    pos_y            = hub_state["pos"][1],
                    pos_z            = hub_state["pos"][2],
                    rpy_roll         = sensor_data["rpy"][0],
                    rpy_pitch        = sensor_data["rpy"][1],
                    rpy_yaw          = sensor_data["rpy"][2],
                    omega_rotor      = omega_spin,
                    tether_tension   = _ti.get("tension",   0.0),
                    tether_length    = _ti.get("length",    0.0),
                    tether_extension = _ti.get("extension", 0.0),
                    tether_slack     = 1 if _ti.get("slack", True) else 0,
                    damp_alpha       = _damp_alpha,
                )
                log.info("%s", _hb.heartbeat(
                    remaining_s=max(0.0, _startup.duration - t_sim)))
                # Extra velocity detail for first 15 s of free flight
                # (helps diagnose kinematic→free-flight transition oscillations)
                t_free = t_sim - _startup.duration
                if 0.0 <= t_free <= 15.0:
                    log.info(
                        "  vel_NED=[%.3f %.3f %.3f] m/s  |v|=%.3f  "
                        "orbit_r=%.2f m  col=%.4f rad  phase=%s",
                        vel[0], vel[1], vel[2], float(np.linalg.norm(vel)),
                        float(np.sqrt(_hb.pos_x**2 + _hb.pos_y**2)),
                        collective_rad,
                        _traj_cmd.get("phase", ""),
                    )

            # ----------------------------------------------------------------
            # Timing: advance sim-clock; sleep remainder in normal mode;
            # record total wall-clock time per step for adaptive speed estimate.
            # ----------------------------------------------------------------
            # t_sim tracks wall-clock elapsed time so fixtures and the kinematic
            # startup complete in real time regardless of physics loop rate.
            # In Docker the BEM loop takes ~20ms/step vs 2.5ms target, so the
            # step accumulator (DT_TARGET per step) would advance sim-time 8x
            # slower than wall clock and cause fixture timeouts.
            t_sim   = time.monotonic() - t_wall_start
            elapsed = time.monotonic() - t_wall_loop
            if elapsed < DT_TARGET:
                time.sleep(DT_TARGET - elapsed)

            # Record wall time per physics step for the adaptive speed estimator.
            _stm.record_sim_step(time.monotonic() - t_wall_loop, DT_TARGET)

            step += 1

    except KeyboardInterrupt:
        log.info("KeyboardInterrupt received — shutting down.")

    except Exception as exc:
        log.exception("Fatal error in main loop: %s", exc)
        raise

    finally:
        # -- Graceful shutdown ------------------------------------------------
        log.info("Final state at step %d (t=%.2f s):", step, t_sim)
        log.info("  pos_NED : %s m",  hub_state["pos"].round(3))
        log.info("  vel_NED : %s m/s", hub_state["vel"].round(3))
        log.info("  omega_spin : %.2f rad/s", omega_spin)

        if _telemetry_file is not None:
            try:
                _telemetry_file.flush()
                _telemetry_file.close()
                log.info("Telemetry log closed.")
            except Exception:
                pass

        log.info("Closing connections ...")
        try:
            sitl.close()
        except Exception:
            pass
        log.info("Mediator stopped.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    args = _parse_args()
    logging.basicConfig(
        level    = getattr(logging, args.log_level.upper()),
        format   = "%(asctime)s %(levelname)-8s %(name)s: %(message)s",
        datefmt  = "%H:%M:%S",
    )
    run_mediator(args)


if __name__ == "__main__":
    main()
