"""
test_steady_flight.py — Steady-state physics test at 30° tether elevation.

The simplest possible flight scenario:

  - Hub starts at the 30° tether-angle equilibrium position (East of anchor).
  - Body Z (rotor axle) is aligned with the tether direction from the start.
  - Collective is set to the open-loop equilibrium value (no ArduPilot).
  - Tether rest length is set so the tether is already taut at the equilibrium
    tension.
  - Wind is steady East.

Because the system starts close to equilibrium (correct position, orientation,
and collective), it should remain near that position.  This is the "simple case"
— no transient from launch, no ArduPilot control loop.

A separate test (test_drift_from_origin, TODO) will cover the harder case of
starting directly above the anchor and letting wind + tether drive equilibrium.

Coordinate frame: NED — X=North, Y=East, Z=Down.  Tether anchor at origin.

steady_state_starting.json is generated by test_generate_ic.py::test_create_ic.
"""
import math
import sys
from pathlib import Path

import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

pytestmark = [pytest.mark.simtest, pytest.mark.timeout(300)]

import mediator as _mediator_module
from aero import rotor_definition as _rd
from simtest_runner import PhysicsRunner, PythonAP
from ap_controller import TensionApController
from pumping_planner import TensionCommand
from simtest_ic import load_ic

TetherModel = _mediator_module.TetherModel

# Load rotor definition — single source of truth for all physical constants.
_ROTOR = _rd.default()
_DYN_KW = _ROTOR.dynamics_kwargs()   # mass, I_body, I_spin

# Design tether equilibrium orientation (from beaupoil_2026.yaml) in NED
# ── Physical constants (all from rotor definition) ────────────────────────────
MASS   = _DYN_KW["mass"]
WIND   = np.array([0.0, 10.0, 0.0])       # NED: 10 m/s East = Y axis
WIND.flags.writeable = False

DT     = 2.5e-3                            # s  (400 Hz)


_DT_CMD        = 0.1   # 10 Hz ground commands
_PLANNER_EVERY = max(1, round(_DT_CMD / DT))                   # 40
_AP_EVERY      = max(1, round(1.0 / (PythonAP.AP_HZ * DT)))   # 8


def _run_simulation(log, steps: int = 4000):
    """
    Run the steady-state physics for `steps` iterations starting from the
    settled IC in steady_state_starting.json.  No warmup needed — the IC is
    already the physics-settled state from test_generate_ic.py.

    Returns a dict of per-step arrays plus scalars.
    """
    ic         = load_ic()
    tension_out = 300.0   # IC targets 300 N midway between reel-in (226 N) and reel-out (435 N)
    target_alt = float(-ic.pos[2])

    # ── Recorded run ──────────────────────────────────────────────────────────
    runner = PhysicsRunner(_ROTOR, ic, WIND, col_min_rad=-0.28, col_max_rad=0.10)
    _ap    = TensionApController(
        ic_pos=ic.pos, mass_kg=MASS,
        slew_rate_rad_s=_ROTOR.body_z_slew_rate_rad_s,
        warm_coll_rad=ic.coll_eq_rad, tension_ic=tension_out,
    )
    ap     = PythonAP(_ap, wind=WIND, dt=DT)
    ap.tel_fn = lambda r, sr: {
        **ap.log_fields(),
        "body_z_eq":  r.hub_state["R"][:, 2],
        "net_moment": np.zeros(3),
    }
    _ap.receive_command(TensionCommand(
        tension_setpoint_n=tension_out, tension_measured_n=runner.tension_now,
        alt_m=target_alt, phase="reel-out",
    ), _DT_CMD)

    t_arr     = np.zeros(steps)
    pos_arr   = np.zeros((steps, 3))
    vel_arr   = np.zeros((steps, 3))
    ten_arr   = np.zeros(steps)
    angle_arr = np.zeros(steps)

    for step in range(steps):
        hub = runner.hub_state
        pos = hub["pos"]
        t_arr[step]   = step * DT
        pos_arr[step] = pos
        vel_arr[step] = hub["vel"]
        ten_arr[step] = runner.tension_now

        R      = np.asarray(hub["R"], dtype=float)
        body_z = R[:, 2]
        tlen   = np.linalg.norm(pos)
        tdir   = pos / max(tlen, 0.1)
        angle_arr[step] = math.degrees(math.acos(float(np.clip(np.dot(body_z, tdir), -1.0, 1.0))))

        if step % _PLANNER_EVERY == 0:
            _ap.receive_command(TensionCommand(
                tension_setpoint_n=tension_out, tension_measured_n=runner.tension_now,
                alt_m=target_alt, phase="reel-out",
            ), _DT_CMD)
        if step % _AP_EVERY == 0:
            ap.tick(step * DT, runner)
        sr = runner.step(DT, ap.col_rad, ap.roll_sp, ap.pitch_sp, runner.omega_body)
        ap.log(runner, sr)

    ap.write_telemetry(log.log_dir / "telemetry.csv")
    return {
        "coll_deg":      math.degrees(ic.coll_eq_rad),
        "omega_spin_eq": runner.omega_spin,
        "pos0":          ic.pos,
        "vel0":          ic.vel,
        "R0":            ic.R0,
        "rest_length":   ic.rest_length,
        "t":             t_arr,
        "pos":           pos_arr,
        "vel":           vel_arr,
        "tension":       ten_arr,
        "axle_deg":      angle_arr,
    }


# ── Test ──────────────────────────────────────────────────────────────────────

def test_steady_flight(simtest_log):
    """Hub stays aloft, tether taut, axle aligned for 10 s from tether equilibrium IC."""
    STEPS     = 4000    # 10 s at 400 Hz
    DRIFT_MAX = 15.0    # m
    AXLE_MAX  = 20.0    # deg

    data = _run_simulation(simtest_log, STEPS)

    pos0  = data["pos0"]
    final = data["pos"][-1]
    drift = np.abs(final - pos0)

    simtest_log.write(
        [f"drift_E={drift[1]:.3f}m  drift_Z={drift[2]:.3f}m  steps={STEPS}"],
        f"drift_E={drift[1]:.3f}m  drift_Z={drift[2]:.3f}m",
    )

    failures = []

    if not np.all(np.isfinite(data["pos"])):
        failures.append("NaN/inf in position history")
    if not np.all(np.isfinite(data["vel"])):
        failures.append("NaN/inf in velocity history")

    if drift[1] >= DRIFT_MAX:
        failures.append(
            f"East drift {drift[1]:.2f} m >= {DRIFT_MAX} m "
            f"(coll={data['coll_deg']:.1f} deg)"
        )
    if drift[2] >= DRIFT_MAX:
        failures.append(
            f"Vertical drift {drift[2]:.2f} m >= {DRIFT_MAX} m "
            f"(coll={data['coll_deg']:.1f} deg)"
        )

    slack_steps = np.where(data["tension"] < 0.01)[0]
    if len(slack_steps) > 0:
        failures.append(
            f"tether slack at {len(slack_steps)} steps "
            f"(first at {slack_steps[0]*DT:.2f} s, "
            f"dist={np.linalg.norm(data['pos'][slack_steps[0]]):.2f} m)"
        )

    violations = np.where(data["axle_deg"] > AXLE_MAX)[0]
    if len(violations) > 0:
        failures.append(
            f"axle misaligned > {AXLE_MAX} deg at {len(violations)} steps "
            f"(first at {violations[0]*DT:.2f} s: {data['axle_deg'][violations[0]]:.1f} deg)"
        )

    assert not failures, "\n  ".join(failures)
