[package]
name = "linkhub-mavio-dialect"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
mavinspect = { version = "0.6.6", default-features = false }
mavlink-message-definitions = { version = "0.6.7", default-features = false, features = ["compress", "dlct-ardupilotmega", "std"] }
serde_json = "1.0"
thiserror = "2.0"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
