export const DISPLAY_TELEMETRY_RATES = Object.freeze({
  ATTITUDE: 25,
  ATTITUDE_QUATERNION: 25,
  ATTITUDE_TARGET: 25,
  SERVO_OUTPUT_RAW: 25,
  LOCAL_POSITION_NED: 10,
  BATTERY_STATUS: 2,
  RPM: 5,
});
